### ISSUE TITLE
Merge and tidy-up contacts feature

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1088]
**Is your feature request related to a problem? Please describe.**

I'm using a sync app on my Android phone. After exporting multiple address books (in my case, one old from owncloud contacts+, one from owncloud and one from Google account), and with the "help" of some contact merge apps on Android, I got three trashcan .vcf files with dozens of duplicates.

Just attached a sample contact file to give a taste of what I mean.

Now, I import this garbage into nextcloud contacts, and absolutely true: sh.t in = sh.t out.

**Describe the solution you'd like**
There should be a tidy-up feature that:
• lets me mark contacts as duplicate and merge them to just one
• even searches my contacts for possible duplicates and asks me what to do
• detects the same field (e.g. ORG, TITLE, ...) defined multiple times in one contact and asks me what to do
• detects the same data in multiple lines (e.g. identical ADR, TEL, ...) and just imports unique fields
• detects malformed address data (often exported by Google Mail) that contains a line break

**Describe alternatives you've considered**
At the moment, I'm cleaning up this junkyard in a text editor what is not funny at all. But what are other people doing?

**Additional context**
sample data
[testkontakt.txt](https://github.com/nextcloud/contacts/files/3139347/testkontakt.txt)

**Comment by skjnldsv** [comment]
Duplicate of #70

**Comment by felixrindt** [comment]
> Duplicate of [#70](https://github.com/nextcloud/contacts/issues/70)

I'm bringing this up again, because with what has been implemented for #70, I wouldn't consider this a duplicate.
I just imported a vcf file with some contacts I did not have, but some I already had in my address book and now have dozens of duplicates. Merging them individually is tedious, especially with #4921. 

I would in fact love a feature that looks for possible duplicates automatically and lets me bulk-merge those, which is one of the things mentioned by OP:

> even searches my contacts for possible duplicates and asks me what to do

I think the Google Contacts Tidy up feature might be good inspiration for how to design this.

Feel free to reopen the issue or tell me to open a new one - specific to duplicate-detection and bulk-merge functionality.
