### ISSUE TITLE
confirmation when delete

### ISSUE THREAD

**Issue by Chialya** [nextcloud/contacts#1262]
I have edit the compiled contacts.js.
want for me an confirm message, when delete anything.

In the contact list is a nice feature to wait 7 sec till the contact will delete finaly.
But this is not good for me. How often a complete contact will be deleted? -> super rare !

So I've removed the "icon-delete" in the contact-list,
so there is no delete icon, like the older visions.

The permanently visible "icon-delete" for all contact-properties is also not good.
(A mobile phone number is quickly deleted by a mistake.)

I've build in a dialog to confirm:
methods:{...  confirmDeleteX:function(){OC.dialogs.alert(t("contacts"," {prop} ",{prop:this.property.name}),t("contacts","Delete ?"),this.deleteProperty,!0)}}

-> The confirmation bevore a property is delete works perfectly!
But the text "this.property.name" is not workling in the message.
Please can help me ?

(@skjnldsv: If you don't want to understand my report, please do not close the reuest immediately. Please give me a chance to explain!)

**Comment by skjnldsv** [comment]
Hey!
We have a template when creating issues, why are you not following it?
This make it much harder for us to understand what you're trying to ask us.

Anyway.  Let's move on.
I will help you here because it looks quite simple, but we don't do custom requests on the code here, because otherwise I will never have enough time on my hand.

Use `OC.dialogs.alert(this.propertyComponent.propModel.readableName, t('contacts', 'Delete ?')...`


Please note that this will prevent you from receiving any future updates vi the usual app store.
Cheers

**Comment by skjnldsv** [comment]
I'm closing it to not confuse others. You can still ask questions here if you want, I will try to see if I can help you.
