### ISSUE TITLE
»Social media« and »Instant messaging« should have all fields which proprietary platforms like Apple Contacts or Google Contacts also offer

### ISSUE THREAD

**Issue by jpvdgiessen** [nextcloud/contacts#130]
At this moment I only can add as Social Media items "Facebook" and "Twitter".
Is there a possibility to add also "LinkedIn" or other Social Media?

**Comment by skjnldsv** [comment]
Thanks! :)
Good idea!

**Comment by xraMsamohT** [comment]
Google+ does not show up in the statistics but I would like it in the selection. Thanks!
https://www.statista.com/statistics/272014/global-social-networks-ranked-by-number-of-users/

**Comment by Spartachetto** [comment]
It could be interesting to have the possibility to add also some decentralized social networks, like 

- diaspora*
- GNU social
- pump.io
- ...

We already have the possibility to add our diaspora* info in the personal profile, it is strange that it is not possible to insert that info for our contacts

**Comment by qwertygc** [comment]
On android we have also Skype

**Comment by jancborchardt** [comment]
Let’s first start with the basics, not all and every single service we can think of. :) Here are the entries iCloud shows, and we should be up to par with that:

For »Social network«:
![screenshot from 2017-07-10 11-38-07](https://user-images.githubusercontent.com/925062/28011981-993e0d5e-6564-11e7-80f8-b82f5a6e5354.png)
Only one thing: Let’s add Instagram since that’s very popular.
All entries have »Username« as placeholder, except Twitter which prepends an @ as you can see.

This is for »Instant messaging«:
![screenshot from 2017-07-10 11-38-42](https://user-images.githubusercontent.com/925062/28012036-c9d84fb0-6564-11e7-88c0-5c08a982dc5c.png)
All entries have »Username« as placeholder.


Afterwards we can add things like Diaspora, Mastodon, and so on.

cc @xh3n1 @jonatoni

**Comment by olantrust** [comment]
**# Messaging platforms**

Agree with @jancborchardt to limit the default entries. But disagree with using iCloud as any kind of basis, most of their messaging network options don't even exist any more (MSN, Jabber, Google Talk)!

There are many popular globally platforms listed below. We must treat them equally according to value to users and not be biased according to our own cultural backgrounds or preferences. 

**_Why don't we include the ones below, but display the top 10, and then include a 'more...' popup?_**

**Here are this years figures for messaging:**
1300 WhatsApp	
1200 Facebook
 877  QQ	
 846  WeChat	
 300  Snapchat	
 300  Skype	
 260  Viber	
 217  LINE	
 210  Kik (now includes Rounds)	
 100 Telegram
 100 BBM	 (Blackberry Messenger, avail on all devices)	
 100 Hike	
   70 Steam (gaming messaging client)	
   60 Discord	
   50 Kakaotalk	
   12 Slack	
   12 Hipchat	
        Hangouts	  Unknown	
        Yahoo	  Unknown	
		
**Let's remove/exclude:**	
   10  ICQ	
     5  AIM	
     5 Gadu Gadu	
     3 Eikon (Reuters)	
     0 MSN (deceased 2014)
     0 Jabber (deceased 2015)
     0 Google Talk (deceased 2017)
        XMS (eBuddy)	- Unknown, used to be in millions

**Comment by olantrust** [comment]
# ** Social platforms

We should base the choice on these figures for 2016-7.

Again we should consider showing the highest ones, and then having a Custom... and More... choice at the end listing the others.

2047  Facebook
1500  Youtube
  800  WeChat (Social)	
  700  Instagram
  638  QZone
  357  Tumblr
  328  Twitter
  313  Sina Weibo
  300  Baidu
  240  Renren
  200  Reddit
  200  Vimeo
  175  Pinterest
  160  Spotify
  125  Steam
  122  YY
  111  Google+
  106  LinkedIn
  100  vKontakte
    65  Odnoklassniki
          Diaspora (unknown)
          Last.fm	(unknown)

**Comment by olantrust** [comment]
**Merge social and XMPP field creation**

It should be noted that the difference between 'XMPP messaging' and Social media is moribund, from a Users perspective.

Almost all the Social platforms listed in the last post have a messaging component (including Twitter, LinkedIn, Instagram). Most of the messaging platforms are now entering social (including Skype, WeChat...)
Others are cross platform (Facebook, Yahoo, Reddit, vKontakte, Steam).

What Users need is not to duplicate information and have a single Social/Messaging field, to prevent doubling their work entering details (or forgetting to).

When they enter a network:
where relevant to the network either:
a) only an XMPP record is created, where only messaging exists
b) only a Social field is created where only social exists
c) both fields are created, with the same username

Splitting them up is a false dichotomy, and doubles the User's work.

The downside, it wouldn't update with external updates, or when a contact was edited. But it would still be better than the current situation.

**Comment by jancborchardt** [comment]
Okay, then let’s list 10. For IM cut after Telegram and for social network cut after reddit (11th cause there’s a bunch of people using it).

**Comment by olantrust** [comment]
Sounds like a plan.

Just three residual questions then:
1) What about in Messaging; with the top 10 do we then leave out Yahoo, Hangouts and Baidu? I searched hard but they are all secretive about the figures (not that any of the figures are highly reliable or comparable - but they do at least give an indication of relative use.)
2) Is it possible to have a 'More...' at the end of the list, listing others, or is that too much - and just have 'Custom' available?
3) When existing contacts are imported or synced with 'MSN' 'Windows Live Messenger' and ' Google Talk', should those be synced to 'Skype' and (for Google Talk) 'Hangouts'? Since all users of those deceased services were ported to those other platforms...

**Comment by jancborchardt** [comment]
For any existing services, the "Custom" name function could just be used to put in the name. Porting of the service sounds quite involved.

In any case, we should list all the services that Google Contacts currebtly includes.

**Comment by olantrust** [comment]
These are the services on the Google Contacts default list. It's pretty outdated alas:

Google Talk (deceased, now merged into 'Hangouts')
AIM  (very low user base, exclude?)
Yahoo (probably should include)
Skype (already on our proposed list)
QQ (already on our proposed list)
MSN (deceased, exclude)
ICQ (very low user base, exclude?)
Jabber (deceased, exclude)

**Comment by jancborchardt** [comment]
@olantrust a contribution in the form of a pull request would be very welcome. :)

**Comment by smonff** [comment]
Just to say that as a Nextcloud user, it looks strange that this list features centralized-proprietary services and don't support the decentralized alternatives. I don't say the proprietary fields should be removed, but I don't know, it is a matter of coherency.

Then maybe the addition of too many fields would make the list too messy. I don't say it's simple either.

Just a point of view, I hope it can be useful. Thanks.

**Comment by jancborchardt** [comment]
@smonff as I mentioned above:

> Afterwards we can add things like Diaspora, Mastodon, and so on.

**Comment by sleepypioneer** [comment]
Hey everyone,
is this issue still relevant or has it been completed with PR #356 ? If not completed what are current thoughts on the direction.
Thanks!
@skjnldsv @jancborchardt

**Comment by skjnldsv** [comment]
This issue is still relevant yes, we're missing some social networks it seems :)
