### ISSUE TITLE
Can't scroll through shared addressbook list

### ISSUE THREAD

**Issue by SIRSteiner** [nextcloud/contacts#14]
If I get many shared contacts (addressbooks) then in settings it is not possible to scroll them.
Please look at the screenshot
![screenshot](https://cloud.githubusercontent.com/assets/3488638/19664088/3b005120-9a3f-11e6-98a8-11cb0ecf9a7d.png)

**Comment by irgendwie** [comment]
@jancborchardt Already told you about that at the meetup! :blush:  Would be cool to have a good looking solution for this. Also @skjnldsv

**Comment by jancborchardt** [comment]
Right! 3 things we need to do:
- [ ] restrict the height of the settings area (should be done in core/css/apps.css), for example to 500px or max 80% height.
- [ ] put the actions in a 3-dot menu because four icons next to each other are difficult to understand
- [ ] ellipsize the names if they are too long so it doesn’t break

cc @nextcloud/designers

**Comment by jakobsack** [comment]
tasks 1 and 3 are ready to be merged. Great work, @pgys !

**Comment by skjnldsv** [comment]
for task 2, I can suggest this again:
![gif](https://cloud.githubusercontent.com/assets/14975046/18564110/787871dc-7b8a-11e6-9a62-90c06acccbaa.gif)

from https://github.com/owncloud/contacts/pull/518#issuecomment-247414277

**Comment by jancborchardt** [comment]
@skjnldsv let’s do it like in the other apps with the popover icons+text. Without the text, 4 icons next to each other are very difficult to understand.

**Comment by skjnldsv** [comment]
Okay, but without texts. Otherwise, we won't have enough space to display the popup and I don't really want to add a big bottom padding 😉

**Comment by jancborchardt** [comment]
What do you mean? The icons need the text for sure, like in all the other menus. :) If there’s not enough space to display the popup menu downwards then we have to make room downwards. We can add the padding depending on if you click the menu so it’s not always there. :)

**Comment by skjnldsv** [comment]
I completely change my view now. I fully agree with you.
I was waiting for my work on the css guidelines. :)
A pr is on its way.

**Comment by jancborchardt** [comment]
@skjnldsv :heart:  :) high five

**Comment by skjnldsv** [comment]
@jancborchardt look at other opened pr on contacts pls :)

**Comment by skjnldsv** [comment]
Anyhow, the popover menu is a bit broken on stable11. Should I backport my apps.css edits?

**Comment by jancborchardt** [comment]
Are they easily backportable with pure CSS and minimal invasion? Backports are only for really important bugfixes, and if it’s sure that it doesn’t cause more bugs. ;)

**Comment by skjnldsv** [comment]
Here's the situation I'm at:
- With the recent popover fix on master12, the popover work works fine
- Since the popover wasn't really well implemented, this is buggy on stable11
- I can add exception in the contacts css, but since we're gonna have one version to rule them all, I don't like duplicate code that won't be used by stable12

So should we backport? Or add css exceptions in contacts, I'm a bit lost 😞

**Comment by irgendwie** [comment]
@skjnldsv should already be fixed, or not?

**Comment by skjnldsv** [comment]
I think so yeah, need to test it.

**Comment by irgendwie** [comment]
#101 is merged, let's close this for now.
