### ISSUE TITLE
Contact changes in activity stream

### ISSUE THREAD

**Issue by Klaas-** [nextcloud/contacts#141]
### Steps to reproduce
1. change a contact
2. not showing in activity stream
3.

### Expected behaviour
changes should show up in activity stream

### Actual behaviour
Not showing up in activity stream

### Server configuration
**Nextcloud version:**  11.0.1

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** updated

```

As a user I would like to see changes to contacts (especially on shared address books) to show up in activity stream or even trigger an e-mail to me. Other apps (calendar for example) already do this.

Thanks!

**Comment by skjnldsv** [comment]
I think this could cause a lot of spam into the activity app. 
And now that I think of it, this should probably be opened into server since dav edits are handled there 😄

**Comment by irgendwie** [comment]
I'm pretty sure for the calendar app this is done within the dav backend in server, since it logs activities from external applications (python caldav client, thunderbird, etc.) for me.

Just for reference:
- https://github.com/nextcloud/server/issues/1662 (contacts trashbin)
- https://github.com/nextcloud/server/blob/9e32885b34dbf6341551ad981365d5d1742a4f65/apps/dav/lib/CalDAV/Activity/Backend.php#L68 (calendar activity "hooks")

**Comment by Klaas-** [comment]
I'll reopen it in server, thanks
