### ISSUE TITLE
Unable to import contacts to AVM Fritz!Box-Router via CardDAV

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/contacts#1417]
There's a new feature for the Routers called "Fritz!Box" by AVM (German devices).
You can import now CardDAV-Addressbooks for use in your home-telephone-devices.
Great - very nice, but it does not really work. Here the result:

Import from Nextcloud 17 / Contacts 3.1.6:

![grafik](https://user-images.githubusercontent.com/6906390/72654149-89e75580-398e-11ea-9d0f-8641f6e184c1.png)
Import from Apple's iCloud:
![grafik](https://user-images.githubusercontent.com/6906390/72654170-aa171480-398e-11ea-88c4-b99334d7a2c9.png)

Here's the Contact:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:98741b8e-4f06-41c6-9b17-5ffdfb9fc5ca
REV;VALUE=DATE-AND-OR-TIME:20200117T233825Z
FN:Adler\, Karen
ADR;TYPE=HOME:;;xxxxxxxxxxxxx;xxxxx;;xxxxx;
EMAIL;TYPE=HOME:
TEL;TYPE=CELL:+49 (xxx) xxxxx
BDAY;VALUE=DATE:1xxxxxxx
N:Adler;Karen;;;
END:VCARD
```

Why is there the "Backslash" at Adler\?

**Comment by mburnicki** [comment]
Hm, The FN: field has the full name with the last name first, followed by the given name, separated by a comma. I think the comma has to be escaped by a ' \' in the raw VCARD text to indicate that it belongs to the string to be displayed. However, the FN has to be unescaped (i.e. the '\' removed) when it is displayed.

So I think it's OK if the comma is in the VCARD text itself, and it **_might_** be a problem in the Fritz!box firmware that it doesn't unescape the FN when it reads the VCARD.

Please note that the order of the first name / given name is different in your screenshots for NC and AC. Is it possible that the FN is stored as "Adler, Karen" in NC, but as "Karen Adler" in Apple Cloud? In this case the FN field from AC includes no  comma that has to be be unescaped before being displayed, so of course this looks right if the bug is in the FB firmware.

Just a few thoughts from another NC user.

**Comment by rakekniven** [comment]
Is this issue still an issue?
Just seen that future firmware of AVM will have native CardDAV support!

That means your contact list in your router will be always up-to-date.
German link: https://avm.de/fritz-labor/frisch-aus-der-entwicklung/frisch-aus-der-entwicklung/

**Comment by skjnldsv** [comment]
Awesome news @rakekniven Thanks for sharing!!

**Comment by rakekniven** [comment]
Firmware v7.20 has been released and it works out of the box!

**Comment by skjnldsv** [comment]
Closing then :)
