### ISSUE TITLE
Nextcloud 18 incompatibility warning

### ISSUE THREAD

**Issue by DidierLmn** [nextcloud/contacts#1429]
### Nextcloud server 18 shows incompatibility warning
......
......

**To Reproduce**
1. Install contacts 3.1.6
2. Upgrade server to 18
3. Contacts automatically gets disabled + shows warning + no available update

**Expected behavior**
Update contacts 3.1.7 should show which lists nextcloud 18 as compatible in info.xml

**Actual behavior**
No contacts 3.1.7 update available (I suspect this is due to #1388)

### Server configuration

**Nextcloud version:** 18.0

**Contacts version:** 3.1.6

**Updated from an older Nextcloud or fresh install:** update from nextcloud 17

**Signing status:** No errors have been found.

**Comment by j-ed** [comment]
I ran into the same problem and found out that the Contacts app seems to have been published twice with a different support range. The installed app 3.1.6 contained the following max-version string:
```
<nextcloud min-version="15" max-version="17" />
```
I downloaded the app manually and first realized the following version discrepancy:

![grafik](https://user-images.githubusercontent.com/2572764/72717529-74338500-3b74-11ea-9342-658c82e0feb6.png)

After extracting the downloaded files to the apps directory, the max-version string has been changed, although the original app version number hasn't been changed, and it was possible to activate the app again.
```
<version>3.1.6</version>
...
<nextcloud min-version="15" max-version="18" />
```
My assumption is, that the version number hasn't been updated after the change has been applied so that the update routine keeps the existing app version.

**Comment by rubo77** [comment]
So how do I have to fix this in my install?

**Comment by j-ed** [comment]
@rubo77 This is an easy task, manually download the app from the app store and extract the contacts folder and all files to the local apps directory. Make sure that the access rights are set correctly, navigate to the Apps menu and reactivate the app - that's all.

**Comment by rubo77** [comment]
Where has this to be fixed? so the versioning is shown correctly in the nextcloud webinterface?

**Comment by skjnldsv** [comment]
Release is on its way

**Comment by rubo77** [comment]
what is the problem while uploading?

**Comment by skjnldsv** [comment]
@rubo77 appstore is having issues

**Comment by skjnldsv** [comment]
Aaand released! :)
Thanks everyone!
