### ISSUE TITLE
Question and Improvement of "Contacts"

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/contacts#154]
I use your demo on NextCloud.com and have a question and enhancement.

1. How I can show the contacts which I have assigned a addressbook? (see screenshot, please)
2. If I create a addressbook, the Label is missing by select an addressbook in the contact form (see screenshot, please)
3. If I create an contact, the placeholder of the name is not deleted, when I will type the name. I must delete "Neuer Kontakt" manually. It is possible to delete it by highlighting the input? (like an "placeholder in HTML5)

Thanks in advance!

![unbenannt-1](https://cloud.githubusercontent.com/assets/1473674/23582289/9f440272-0127-11e7-95b6-3d688e67ec85.png)

**Comment by irgendwie** [comment]
1. The addressbook of the contact is visible in the details (right circle), otherwise it currently is not possible to only show contacts of a specific addressbook (ref https://github.com/nextcloud/contacts/issues/36)
2. There is no label in the current state of the app, but it would make sense to add one! :+1: @skjnldsv 
3. Sounds good to me! :+1:

**Comment by skjnldsv** [comment]
Indeed

**Comment by Dennis1993** [comment]
Thank you very much!

**Comment by jancborchardt** [comment]
Nr 3 is a regression:

- There should not be any text »New contact« in the input field for the name.
- The name field should be automatically focused after pressing the new contact button

**Comment by skjnldsv** [comment]
@jancborchardt It's not really a regression. Since a FN field MUST be present on a vcard, we force the field to be set with a string (New Contact in that case). We can't remove the value.

**Comment by jancborchardt** [comment]
@skjnldsv hm, then just don't save before a name is put in?

Or at least on creation select the whole contents of the »New contact« field (which should be called »Name« like the placeholder because otherwise it’s confusing) so simple typing will erase the contents with whatever you type.

**Comment by skjnldsv** [comment]
That's what I put on the adr/tel/mail pr  of the railgirls. :) 
We need to create a local object without a synchronization until edited. 

But the issue still applies. A FN field is required  so we need to prevent the sync until the fn field is filled. This could confuse the user since he won't know that and can loss all other data he entered until the fn is valid.

**Comment by jancborchardt** [comment]
> This could confuse the user since he won't know that and can loss all other data he entered until the fn is valid.

How about we just call it »Name« by default then?

**Comment by skjnldsv** [comment]
We can, but I find it less understandable than New Contact though. :) 
Anyhow, let's wait for rails commits to hit master. If they implement the temporary contact, this discussion will be irrelevant ;)
