### ISSUE TITLE
Release version for NC 20

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/contacts#1771]
Well, the title says it all. A version of Contacts supporting NC 20 is required.

**Comment by skjnldsv** [comment]
![Capture d’écran_2020-09-04_12-13-48](https://user-images.githubusercontent.com/14975046/92228391-1a37c380-eea8-11ea-9281-6f6a777e08d8.png)
Clever ;)

Yes, I'm delayed because I'm waiting for external input before release.
You can upgrade to 20 by forcing the app compatibility. A new 2.4.0 will follow soon enough :)
