### ISSUE TITLE
Possibility to sort by last name

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#18]
Especially in a business use case, contacts are often sorted by last name.

Since this is a setting you are likely to set once and forget, it is fitting for the bottom left settings area. As a dropdown like so:

> Sort by [First name ▾]

Default to »First name«, with option for »Last name«.

cc @nextcloud/contacts @Bebef @palegrand

(@irgendwie do you consider this a starter issue maybe? :)

**Comment by palegrand** [comment]
This would be very, very usefull!

**Comment by Offerel** [comment]
+1

**Comment by brjhaverkamp** [comment]
+1=4

**Comment by j-ed** [comment]
👍 I'm looking forward to see that option being implemented, because the currently used default "full name" leads to a sorting based on a given title, e.g. `Herr Bob Marley`, `Herr Michael Jackson`, `Herr Tom Jones`, etc., which is not really comfortable.

**Comment by kvoit** [comment]
Apparently, this is a problem which is fixed in principle, at least in the Owncloud repository. https://github.com/owncloud/contacts/pull/437
I am absolutely puzzled how this situation could come up in the first place, let alone it not being fixed for such a long time. The current single name field renders Nextcloud contacts totally useless for me and anyone with profession contacts ...

**Comment by jancborchardt** [comment]
@nextcloud/contacts any input here? :)

**Comment by skjnldsv** [comment]
I planned it for 1.5.3 if I have enough time :)

**Comment by skjnldsv** [comment]
fixed by #121
