### ISSUE TITLE
Tooltips for Contact Picture options

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/contacts#183]
See: https://github.com/nextcloud/documentation/pull/397#discussion_r108063409

@nickvergessen

**Comment by skjnldsv** [comment]
I'm not sure this is the correct way to indicate this. 🤔
@jancborchardt

**Comment by radoeka** [comment]
This issue is marked with "good first issue".  Not that I'll get involved in this issue, but I don't get what needs to be fixed (btw I followed the link mentioned in the initial issue description).

For a first good issue, I expect a better decription, one that does not require someone to get involved to figure out what is actually asked.  Just my 2ct, I could be wrong.

**Comment by Henni** [comment]
@radoeka an important part of getting started with participating in an open source project is communicating with the existing team. But independently from this I agree that a bit of additional info doesn't hurt:

-------
![](https://raw.githubusercontent.com/nextcloud/documentation/5841f422c53c7e2caf0707a8bf9af465171c13bc/user_manual/images/contact_picture_options.png)
Nextcloud contains a tooltip library which should be reused for this task.

**Comment by skjnldsv** [comment]
Is this only what this issue is about?
I thought this issue was about putting the options in a popover menu. This is much easier than expected! 😂
