### ISSUE TITLE
Allow plain-text input for dates

### ISSUE THREAD

**Issue by isdnfan** [nextcloud/contacts#1865]
Adding a birthday to contact is too complicated as the property doesn't accept free input and is limited to the date-picker widget. The widget default to the current date so it is necessary to scroll for lot of year to select the birthday of the contact.

It would be much easier to enter the birthday using free text. The challenge of parsing the text into valid date could be addressed by displaying valid templates like **dd.mm.yyyy** or **mm/dd/yyyy**

Nextcloud 19.0.3 Contacts 3.4.0.

**Comment by call-me-matt** [comment]
I agree, text input should be possible!

By reading your comment, it seems you are scrolling through the years manually one by one. At least that's what I did in the beginning, until I discovered one can simply click on the year:

![birthday](https://user-images.githubusercontent.com/34400929/96502589-4d64c500-1252-11eb-8b30-fd56ec9f0be8.gif)

**Comment by jangop** [comment]
This is probably one of the biggest issues I have with the current Contacts. In my opinion, text input should take precedence over a date picker, because it is faster (arguably), can be copied & pasted conveniently, and does not require an extra click on `OK`.

Of course, this does raise the common question of how to process dates input as plain text, especially considering that partial dates (e.g., without year, or without day, or only year) are valid values. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) mitigates this issue well, and I think it should be used here (cf. https://tools.ietf.org/html/rfc6350#section-4.3.1):

|                            |              |
|----------------------------|--------------|
| Date                       | `2020-10-30` |
| Date without year          | `--10-30`    |
| Date without day           | `2020-10`    |
| Date without month and day | `2020`       |

**Comment by jangop** [comment]
Maybe rename this issue as `Allow plain-text input for dates`.

**Comment by meonkeys** [comment]
Could we copy the date picker used for when you set an expiration date for a shared file/folder (I think it is the "File sharing" app)? That accepts typed-in dates like `2020-12-30`, and also has a graphical date picker.

**Comment by skjnldsv** [comment]
> Could we copy the date picker used for when you set an expiration date for a shared file/folder

This is the same used :)

**Comment by meonkeys** [comment]
> This is the same used :)

Oh, that's odd, that other date picker *does* accept typed-in date strings.

**Comment by jangop** [comment]
> > This is the same used :)
> 
> Oh, that's odd, that other date picker _does_ accept typed-in date strings.

Very odd indeed. The two pickers also use different format to display current values. 🤔

**Comment by skjnldsv** [comment]
The format is different yes.
I think we use a slightly different config for it :)

https://github.com/nextcloud/contacts/blob/ada212cbd1a5beaacee2a87a4d706387ae72222a/src/components/Properties/PropertyDateTime.vue#L54-L66
https://github.com/nextcloud/server/blob/0c7cc95b4ec3a7ceba3f5067bd03b0d87ecfd0cd/apps/files_sharing/src/components/SharingEntryLink.vue#L240-L260

https://github.com/nextcloud/nextcloud-vue/blob/31bd9cbe60e77525873f7ae7d802b6dc276d6585/src/components/ActionInput/ActionInput.vue#L56-L66

**Comment by Martmists-GH** [comment]
Sorry to reply to an old issue, but I just ran into this and couldn't seem to get it working, despite apparently being resolved:

dd/mm/yyyy
<img width="591" height="156" alt="Image" src="https://github.com/user-attachments/assets/fa3e654e-cf6b-4a07-b90b-c07cee26d359" />

yyyy-mm-dd (as proposed in this thread)
<img width="600" height="161" alt="Image" src="https://github.com/user-attachments/assets/49a10c48-217e-4fe2-8b9a-df24cedaaab4" />

Both clear the field except for the first number when navigating away from it.
