### ISSUE TITLE
Fields with customized name disappear from the UI

### ISSUE THREAD

**Issue by vince-from-nice** [nextcloud/contacts#1997]
### Describe the bug

As soon as I customize a field name like adresse, phone or email (instead of using a predefined name like "Home", "Work" or "Other") the field disappears from the UI. The field is not more visible even if I refresh the page.

Fortunately the data are preserved in database and if I download the VCF file all the fields are present.

**To Reproduce**
1. Go to contact app
2. Click on an existing user
3. Customize an existing field name such as adresse, telephone or email
4. The field disappears !

**Expected behavior**
The modified fied should be stay visible with its customized name.

**Actual behavior**
The modified fied disappaears.

### Server configuration

**Operating system**: 

Linux

**Web server:** 

Apache

**Database:** 

PostgreSQL

**PHP version:** 

7.3

**Nextcloud version:** 

20.0.4

**Contacts version:** 

3.4.2

**Updated from an older Nextcloud or fresh install:** 

Updated from NC 19

### Client configuration
**Browser:**

Firefox ESR 78.6

Chromium 83.0

**Operating system:**

Debian testing

**CardDAV-clients:**

### Logs

I cannot see any logs in the browser. 

I don't have access right now to my NC instance but I will post the NC logs if there are.

Edit: on NC side there are 10 logs like that as soon as the issue occurs:
`Deprecated event type for \OCA\DAV\CardDAV\CardDavBackend::updateCard: Symfony\Component\EventDispatcher\GenericEvent is used`

**Comment by sushidave** [comment]
FYI - Noticing this bug in a Nextcloud 18.0.13 too, but not in a Nextcloud 17.0.7.

**Comment by pongraczi** [comment]
Similar situation with NC 20.0.8  
Additional clients:  
* I use recent Thunderbird (78.8.1) TBsync (2.20) + CalDAV & CardDav service (1.24) under win10
* Evolution 3.36.4-0ubuntu1 under Linuxmint

My experiences:  
* Fields added/labelled (work/home etc.) from Evolution does not show in NC / TB
* Fields added/labelled from TB does not show on NC/Evolution
* Exporting the contact from NC seems contains all fields, but with strange format
  * IMPP;VALUE=UNKNOWN;TYPE=SKYPE:skype:XXXXXX
  * IMPP;VALUE=UNKNOWN;X-SERVICE-TYPE=SKYPE:skype:XXXXXX
  * or Firstname Lastname swapped in TB/NC/Evolution

Expected:
* Fields are shown with correct labels
* Fields saved under TB should appear in NC and should appear in Evolution, too

I guess (because I did not check the DB behind NC) all data saved into the DB, but not shown on the UI and some data loss should exists (label for skype/tel), missing fields in the UI etc.

**Comment by tobiasfrejo** [comment]
I just updated the contacts app from 1.4.3 to 1.5.1 and fields with custom lables are now showing. Seems like #2064 which was included in 1.5.0 fixed the problem.

**Comment by langfingaz** [comment]
I can confirm that the recent version fixed this for me as well (v3.5.2 on NC 20.0.8). Multiple addresses, phone numbers, etc. are now visible :smiley:

**Comment by vince-from-nice** [comment]
Yes the field values are now visible again, but the customized labels are still not showed. 
Even if I choose one of the predefined labels (Home or Work) they are not displayed.
And if I choose "Other", I cannot customize the label like it was possible before...

**Comment by pongraczi** [comment]
Evolution client has some fields, not visible on the webui (NC 20.0.8, v3.5.2) and Thunderbird either:  
* X-SKYPE;X-EVOLUTION-UI-SLOT=1:**masked**
* X-EVOLUTION-FILE-AS:Pongrácz\, István        (this is not critical)

The following fields are visible in the webui and in the Thunderbird, too, but not visible under Evolution:  
* IMPP;VALUE=UNKNOWN;TYPE=SKYPE:skype:**masked**
* IMPP;VALUE=UNKNOWN;X-SERVICE-TYPE=SKYPE:skype:**masked**

All the 4 fields are mentioned above are visible in the downloaded VCARD v3.0, actually I copied these fields from the exported vcard file
