### ISSUE TITLE
Contacts available on the UI not shown in iOS contacts

### ISSUE THREAD

**Issue by SireWellington** [nextcloud/contacts#1998]
Hi

Having hosted my own NC since 2017 (currently 20.0.4 via Docker container based upon standard image from hub.docker.com) I found that some contacts from address books maintained don't show up at all in my iOS device while the majority of the others do.

I have not found any pattern yet though - any similar observations or suggestions how to fix that?

Thanks and best regards
Axel

**Comment by cvinhaes** [comment]
I've been dealing with similar issue, I managed to push some of them by exporting, deleting address related info (ADR) in the file, deleting the contact and imparting from the changed file. Not sure if related with other issue mentioning address info is out of order, though, but I also have this problem.

**Comment by skjnldsv** [comment]
Please share the said contacts :)
You can obfuscate some data if you want as long as the layout and properties stays unchanged

**Comment by cvinhaes** [comment]
Here is the export for the particular contact, this is not the only one, btw. Personal data was obfuscated:
-------------------------------------------------------
BEGIN:VCARD
VERSION:3.0
FN:Bexxx Ghixxx
N:Ghixxx;Bexxx;;;
EMAIL;TYPE=INTERNET:bexxx@xxxxtecbrasil.xxx.xx
EMAIL;TYPE=INTERNET:bexxx.ghixxx@xxxxtecbrasil.xxx.xx
TEL;TYPE=CELL;VALUE=UNKNOWN:(000) 99983-0000
TEL;TYPE=HOME;VALUE=UNKNOWN:(000) 2496-0000
TEL;TYPE=WORK;VALUE=UNKNOWN:(000) 99130-0000
TEL;TYPE=WORK;VALUE=UNKNOWN:(00) 2240-0000
**ADR;TYPE=HOME:;Jardim Botanico;Apt 000 00 Rua Frei Leandro;Rio De Janeiro;;
 ;Brasil;Rua Frei Leandro\, 00 Apt 000\nJardim Botanico\nRio De Janeiro\nBra
 sil**
ITEM1.ORG:Xxxxtec
ITEM1.X-ABLABEL:
BDAY;VALUE=DATE:19740312
URL:linkedin\\://#profile/00000020
ITEM2.X-ABDATE:20030727
ITEM2.X-ABLABEL:_$!<Anniversary>!$_
PHOTO;VALUE=BINARY:https://xxx.googleusercontent.com/-0000Bmy7ymk/Wg-FPQhXc
 NI/AAAAAAAAAAA/xq6yNzQQ-ZEOfoo-oMfqa_uuJ0-cp4KgwCOQUUUU/photo.jpg
CATEGORIES:
UID:a4002042-e557-469d-a620-52ceae6ecaa1
REV;VALUE=DATE-TIME:20210112T110112Z
END:VCARD
------------------------------------------------------
The contact above will not sync with iPhone (iOS 13.3 in my case) unless I delete all address data. Either deleting in NC contacts web UI or in the exported file and reloading it will work. Removing the "ADR" line was all I did.

I have also realized that address information edited in iPhone will not sync back to NC, i.e. if I add address data in the iPhone contact it will not show in NC.Also address line 1 and line 2 are reversed when the contact flows from NC to iPhone.

**Comment by cvinhaes** [comment]
Here is the export for the particular contact, this is not the only one, btw. Personal data was obfuscated:

BEGIN:VCARD
VERSION:3.0
FN:Bexxx Ghixxx
N:Ghixxx;Bexxx;;;
EMAIL;TYPE=INTERNET:bexxx@xxxxtecbrasil.xxx.xx
EMAIL;TYPE=INTERNET:bexxx.ghixxx@xxxxtecbrasil.xxx.xx
TEL;TYPE=CELL;VALUE=UNKNOWN:(000) 99983-0000
TEL;TYPE=HOME;VALUE=UNKNOWN:(000) 2496-0000
TEL;TYPE=WORK;VALUE=UNKNOWN:(000) 99130-0000
TEL;TYPE=WORK;VALUE=UNKNOWN:(00) 2240-0000
ADR;TYPE=HOME:;Jardim Botanico;Apt 000 00 Rua Frei Leandro;Rio De Janeiro;;
 ;Brasil;Rua Frei Leandro\, 00 Apt 000\nJardim Botanico\nRio De Janeiro\nBra
 sil
ITEM1.ORG:Xxxxtec
ITEM1.X-ABLABEL:
BDAY;VALUE=DATE:19740312
URL:linkedin\\://#profile/00000020
ITEM2.X-ABDATE:20030727
ITEM2.X-ABLABEL:_$!<Anniversary>!$_
PHOTO;VALUE=BINARY:https://xxx.googleusercontent.com/-0000Bmy7ymk/Wg-FPQhXc
 NI/AAAAAAAAAAA/xq6yNzQQ-ZEOfoo-oMfqa_uuJ0-cp4KgwCOQUUUU/photo.jpg
CATEGORIES:
UID:a4002042-e557-469d-a620-52ceae6ecaa1
REV;VALUE=DATE-TIME:20210112T110112Z
END:VCARD

The contact above will not sync with iPhone (iOS 13.3 in my case) unless I delete all address data. Either deleting in NC contacts web UI or in the exported file and reloading it will work. Removing the "ADR" line was all I did.

I have also realized that address information edited in iPhone will not sync back to NC, i.e. if I add address data in the iPhone contact it will not show in NC.Also address line 1 and line 2 are reversed when the contact flows from NC to iPhone.

**Comment by towabo** [comment]
Facing exactly the same issue as describes by @cvinhaes .
Contacts with Address Data in NC are not synced to iOS Device at all.
Maintained Address Data on iOS is not synced to NC.
In my case iOS 14.3 | Contacts 3.4.3 
Cheers!

**Comment by MiFiWe** [comment]
Facing similar issues.

**Comment by trvrcr** [comment]
facing same issues,
Seems to be conflicting over the "Item1" parts of the vcard.

BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 14.3//EN
N:Lxxx;Axxx;;;
FN:Axxx Lxxx
NICKNAME:Axxx
EMAIL;type=INTERNET;type=HOME;type=pref:axxx@hxxx.xx
TEL;type=CELL;type=VOICE;type=pref:+xx (0) 4xx 7x xx xx
item1.ADR;type=HOME;type=pref:;;Jxxx Xxxxxxxxxxxxxx 71;Xxxx;Xxxxxxxx;x5xx;Bxxxxx
BDAY;value=date:19xx-xx-xx
PHOTO;ENCODING=b;TYPE=JPEG;X-ABCROP-RECTANGLE=ABClipRect_1&53&803&384&384&JV2uDY6LxzBfE3rUw8UWhg==:
**Removed Photo information***
REV:2021-01-17T12:50:03Z
UID:dxxxxxxx-6xxx4-4xxx4-89xx5-7xxxxeexxc2b
CLASS:PUBLIC
CATEGORIES:Qxxxx,Kxxx,Fxxxxx
X-IMAGETYPE:PHOTO
X-IMAGEHASH:JV2uDY6LxzBfE3rUw8UWhg==
END:VCARD

**Comment by captainfodder** [comment]
I too am having this issue and have found the solution to be removing the address data from the contact in the Nextcloud GUI (NC-GUI) will then allow the contact to sync to the iPhone almost immediately. I believe this issue is related to another issue ([issue #1900](https://github.com/nextcloud/contacts/issues/1900)), but I could be mistaken. 

So far it looks like this issue specifically occurs when the contact was imported from Gmail/Google with Address information. If delete the address property from the NC-GUI and then rebuild it the contact will then sync over correctly.

**This is the vcard exported from NC with the gmail-import data:**
`BEGIN:VCARD
VERSION:3.0
FN:FirstName LastName
N:LastName;FirstName;;;
TEL;TYPE=CELL;VALUE=UNKNOWN:5555555555
UID:3xxxbxxx-1xxx-4xxx-8xxx-2xxxxxx72xx3
REV;VALUE=DATE-AND-OR-TIME:20210329T191218Z
CATEGORIES:Gmail Export 06/16/2020
ADR;TYPE=HOME:;;123 Easy St;CityName;NY;12345;United States;123 Easy
 St\nCityName\, NY 12345\nUnited States
END:VCARD`

**This is the vcard exported from NC after deleting the address and then re-adding it:**
`BEGIN:VCARD
VERSION:3.0
FN:FirstName LastName
N:LastName;FirstName;;;
TEL;TYPE=CELL;VALUE=UNKNOWN:5555555555
UID:31xxxxx4-1xxx-4xxx-8xxx-2xxxxbxxxx93
REV;VALUE=DATE-AND-OR-TIME:20210329T194117Z
CATEGORIES:Gmail Export 06/16/2020
ADR;TYPE=HOME:;;123 Easy St;CityName;NY;12345;United States
END:VCARD`

**This is the vcard exported from iPhone:**
`BEGIN:VCARD
VERSION:3.0
FN:FirstName LastName
N:LastName;FirstName;;;
TEL;TYPE=CELL:5555555555
ADR;TYPE=HOME:;;123 Easy St;CityName;NY;12345;United States
END:VCARD`

**Comment by trvrcr** [comment]
Has this issue been resolved?
