### ISSUE TITLE
contact not found when starting from maps

### ISSUE THREAD

**Issue by droogi** [nextcloud/contacts#2050]
Hello, i found some mistake during editing my contacts:

i display my contacs in "Karten" maps, i click twice on an contact - open in adress book.
it switches to contacts, message "loading contacts", and then top right two error messages appear: group not found & contact not found.
my complete adress list is displayed.

i dont know which log file to attach.
Regards, droogi

**Comment by skjnldsv** [comment]
cc @eneiluj

**Comment by eneiluj** [comment]
Hi,

I'm not sure I get what happens to you. Did you click on the contact in the Maps app and then click on the "Open in Contacts" link in the popup?
Could you give us the target URL of this link? (right click -> copy link location)
Those links should to be fixed in the Maps app. This is most likely not related with the Contacts app. Hopefully there will be a Maps release in one or two months.

**Comment by droogi** [comment]
Hi Eneiluj,

yes, thats what i did. here are the target urls for 2 new contacts, second contact is in a group, first contact not. 
both times i get 2 error messages: group not found, contact not found.

https://myserver/nextcloud/apps/contacts/All%20contacts/ffad58b2-81b1-4616-a98f-1ce336f15806~contacts
https://myserver/nextcloud/apps/contacts/All%20contacts/a0e25d90-3323-4983-831f-2167faf8a1b1~contacts

![image](https://user-images.githubusercontent.com/4030579/108338738-e42c9880-71d6-11eb-949e-3899769b462e.png)

**Comment by eneiluj** [comment]
Thanks for the feedback. At the time this link generation was implemented it was not possible to get a direct link to a contact in Contacts app. It is now possible and will be fixed in next Maps release. Could you create an issue in [Maps issue tracker](https://github.com/nextcloud/maps/issues/)? Or check if there is one about that topic already?
