### ISSUE TITLE
Unreadable QR Code when using Dark Mode.

### ISSUE THREAD

**Issue by trujillojuan** [nextcloud/contacts#2139]
When Dark Mode is enabled from Accessibility Settings, the QR code generated for the contact, shows in grey background and the code is black so it is unreadable. 

![Screenshot 2021-03-27 203130](https://user-images.githubusercontent.com/80686884/112737751-93c5fa80-8f3b-11eb-94ad-e326af104c34.png)

**Comment by Lippe** [comment]
I guess this issue got already "accidentally" fixed by @skjnldsv in commit https://github.com/nextcloud/contacts/commit/bb5f38e9231b659f348fbd83422af0d65194037b and can therefore be closed.
https://github.com/nextcloud/contacts/blob/922f5dd146d946ebe4cf2efe2ced372a71a2b7e9/src/components/ContactDetails.vue#L792-L801
