### ISSUE TITLE
FEATURE REQUEST: Caching for Contact Avatars

### ISSUE THREAD

**Issue by phoenixtechnam** [nextcloud/contacts#228]
Hi all,

I use high-quality avatar images on most of my contacts to make them look great on the phone (synced via connector app).
But in the Browser it takes now quite a long time to load the contacts page/lists. Also every time when I access contacts in the browser, it loads 4-5 MB of data because of the images (which are delivered inline).

That becomes more and more inconvenient in both time and data spend when using the browser.

I made changes to the code in apps/contacts/templates/contact.html to  stop delivering pictures in the ContactList but whatever I change, nothing reflects in the browser. Kindly help me out on this.

Either make avatar images cachable in general or don't show avatars in the ContactList and instead load them via AJAX or so when opening ContactDetails.

Thank you very much.

**Comment by irgendwie** [comment]
@phoenixtechnam this is already implemented by https://github.com/nextcloud/contacts/pull/88 and will be in the next release of contacts. Unfortunately this only works for nextcloud 12 - for nextcloud 11 or lower there isn't much we can do since the dav backend is in nextcloud/server and needed patches for this feature won't be backported.
