### ISSUE TITLE
Importing address book from file works only partially because import breaks process limit in shared hosting environment

### ISSUE THREAD

**Issue by mapausch** [nextcloud/contacts#235]
### Steps to reproduce
1. export addressbook, e.g. from ownCloud into a file
2. import file into Nextcloud address book
3.

### Expected behaviour
All contacts that are in the export file should get imported into Nextcloud address book

### Actual behaviour
Import only works for a part of the contacts.
The others fail with HTTP error 503 (Service unavailable)

Background:
My webhoster has a limit of 8 processes that can run in parallel for my domain. Especially in shared hosting environments such limits are very common. The contacts app creates a HTTP request for every contact and sends all requests in parallel. 
This causes that a lot of contacts can not be imported because the webserver responds with 503 everytime when process limit is reached.

![grafik](https://user-images.githubusercontent.com/18686836/27264080-52dfb022-5477-11e7-8731-699b58450422.png)

**Comment by knut-hildebrandt** [comment]
Hm, I'm not sure if this is the same bug. But the behaviour I experienced is similar. I exported the address book from my nextcloud, deleted it on the server and re-imported it. Less than 15% of the contacts were imported. Tried it several times and it always was the same. Then I had a short look at the exported VCard-file and saw that:

1. it was somehow mixed and held version 3.0 AND 4.0 vcards
2. the majority of the vcards had several - up to five - VERSION entries, all looking the exactly the same for one vcard
3. many of the vcards had several PRODID entries, some of them up to three or four. All of these entries were generated by different clients 

Somehow I had the idea that vcards with more than one VERSION and PRODID entry were not imported. Thus I deleted all of these entries and all of a sudden I was able to import the contacts. Only seven got missing. No clue why is that, because I did not get any error message.

Now I wonder why the vcards are exported in a mixed format file and why leftover entries are not stripped from them. Thus, I suppose, problems like the one I experienced probably could be avoided. Or should better the import process be changed?

**Comment by knut-hildebrandt** [comment]
Back again. Since I ran into more problems while synchronizing with my KDE DAV-Groupware client I edited the vcard file even more. During this process I noticed why these seven vcards were not imported. A CR-LF got missing when I had edited the file manually. Well to make a long story short, when I tried to import the vcard file again I ran into exactly the same problem initially explained in this post. The import process got stuck after importing about 200 to 500 addresses. It never got any further again. My workaround: I split the vcard file into blocks of one hundred addresses and imported all files separately. That worked in the end, but is not really convenient.

And there is still the problem that vcards are not imported correctly after exporting them due to some syntactical error, even though the contacts were visible and could be edited using the nextcloud web interface.

**Comment by mapausch** [comment]
I think you hit another bug.
Already had contact with my webhoster and they said it's too much parallel requests that are sent. And for me it's always another number of contacts that are failing to import. At every attempt it's between about 50 and 100 contacts that can not be imported (out of about 180 contacts). 
I have the same issue with the calender import. Also fails partially because of reaching process limit.

**Comment by knut-hildebrandt** [comment]
I think so too. At first glance it looked a bit like yours but later it turned out that it definitely different. But I experienced your bug as well. Only difference, I can import between 250 and 500 contact at a time. And you are right, they differ with each try.

**Comment by skjnldsv** [comment]
@knut-hildebrandt I'm so sorry, I was on mobile writing a comment and I misclicked and removed your comment.  So sorry, the desktop view on Chrome for Android makes everything far too small!! :(

**Comment by skjnldsv** [comment]
For this thread, I think we should add a retry option for failure like this. Shouldn't be too hard. 
Or an auto retry until all requests are processed or refused for incompatibility! :)

**Comment by mapausch** [comment]
Just FYI. In the calendar app I hit the same thing:
too much parallel requests cause HTTP 503 leading to the effect that only some of the calendar entries get imported (https://github.com/nextcloud/calendar/issues/445)

So maybe it's desirable for NC to implement the same logic in both apps... :-)

**Comment by skjnldsv** [comment]
Hum, dug up and found that no browser allows more than 8 simultaneous requets per host! 
![max-browser-parallel-connection](https://user-images.githubusercontent.com/14975046/28664648-667223e6-72c1-11e7-8d65-8c3c4420b23a.png)

So you might have to edit your config file to destroy process or something like that, I don't know 🤔 

http://sgdev-blog.blogspot.nl/2014/01/maximum-concurrent-connection-to-same.html

**Comment by mapausch** [comment]
sorry, maybe I'm wrong, but from my view it doesn't seem to have to do with a limitation (max parallel connections to a server) in my browser (Firefox 54).

- If it were caused by a limit in my browser than I wouldn't get HTTP 503 errors from the webserver.
- already had contact with support of my webhoster. I created a test account for them and they also tried the import and said that the import reproducible reaches the process limit that's configured for my hosting tariff.
- for test I configured "network.http.max-persistent-connections-per-server" in Firefox to 300 (default is 6). Didn't change anything. Still all requests are sent in parallel and still the same amount of contacts that cannot be imported. 
- during import there were never more than 3 parallel connections established (checked with _netstat | <ip_of_my_domain> | wc l_   )


In my opinion a good solution would be to don't send all requests in parallel.
A little better (because more flexible) would be if the limit of parallelism would be configurable in some way... :-)

**Comment by steineiche** [comment]
Hallo und ein Dankeschön an die Entwickler. Ich finde die Integrationsmöglichkeiten in der nextCloud einfach toll! Bei der Kontakt App würde ich mir wünschen, eine Kontaktliste, die ich per Mail erhalten habe gleich aus der Mail in das Adressbuch zu importieren. Genauso wie eine ics Datei aus der Mail gleich in den Kalender importiert werden kann. Es wäre wirklich klasse wenn das möglich werden würde. Hoffentlich bin ich mit meiner Bitte richtig hier? Danke.

**Comment by skjnldsv** [comment]
@steineiche please use English! :)

**Comment by steineiche** [comment]
OK, here is my google-english :-)
Hello and thanks to the developers. I find the integration possibilities in the nextCloud just great! With the contact app I would wish to import a contact list, which I received by mail directly from the mail into the address book. Just as an ics file from the mail can be imported directly into the calendar. It would be really great if this would be possible. Hopefully I am right here with my request? Thank you.

**Comment by skjnldsv** [comment]
@steineiche this should me in the mail app. I think there is already an issue there! :)

**Comment by skjnldsv** [comment]
Fixed on 3.0.0
