### ISSUE TITLE
Non-iso8859-1 characters as group name not possible

### ISSUE THREAD

**Issue by kesselb** [nextcloud/contacts#2366]
### Describe the bug

Using an emoji as group name is not possible

**To Reproduce**

- Click "Create group"
- Enter 💩💩💩
- Save group
- Add a contact to the group

**Expected behavior**

Contact is added to group

**Actual behavior**

Contact is **not** added to group

```
ContactsPicker.vue?vue&type=script&lang=js&:151 TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.
    at setRequestHeader (xhr.js:125)
    at Object.forEach (utils.js:253)
    at dispatchXhrRequest (xhr.js:119)
    at new Promise (<anonymous>)
    at xhrAdapter (xhr.js:13)
    at dispatchRequest (dispatchRequest.js:52)

```

**Screenshots**

https://user-images.githubusercontent.com/3902676/126529036-d60ba502-ac26-4261-b403-cddb5afb8a7c.mp4

**Comment by aptiko** [comment]
This problem doesn't exist only for emojis, but for all non-iso8859-1 characters. Greek characters won't work. The message I'm getting in the JavaScript Console (Nextcloud 23.0.0, Firefox 97.0) is "TypeError: XMLHttpRequest.setRequestHeader: Cannot convert argument 2 to ByteString because the character at index 0 has value 916 which is greater than 255."

Could someone with appropriate permissions please update the title of this issue? It's way more serious than not being able to use emojis.

**Comment by kesselb** [comment]
It seems to work with the latest main branch. Which version of contacts are you using?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@kesselb, how is that possible to ascertain? Because I am identically affected, I expect that my version is as useful as the reporter's.
