### ISSUE TITLE
Can a new "Nextcloud User" field be added?

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [nextcloud/contacts#242]
It looks as if RFC 6350 allows for proprietary fields. This field could be used by the server components to match a user to a contact, and display only a single entry in the contacts menu.

**Comment by alexanderdd** [comment]
Yeah it's also a little counter-intuitive that Nextcloud users don't appear in contacts (have to be added by hand)

Thanks for your work everyone!

**Comment by mburnicki** [comment]
@alexanderdd I'm maintaining an owncloud/nextcloud instance for a couple of independent cloud users. Each of them has their own address book(s), but the address book of a specific cloud user usually includes his own contacts, but not necessarily other cloud users.

Most of them don't even know each other, and I doubt that they want to have entries for all other cloud users in their address book by default. Also, I think it may be hard to figure out the relationship between an address book entry and an individual cloud user account automatically in a safe way.

Of course, if you have a working group where users know each other, and each of them also has a cloud account then it may make sense to have an entry with the cloud user name. However, IMO this entry should be optional, so that you can add the information by yourself. For now, you could just write the cloud user name into the "notes" field of the associated address book entry.

**Comment by skjnldsv** [comment]
I think I saw a pr on server about providing an addressbook for all the nextcloud users 🤔

**Comment by alexanderdd** [comment]
This actually needs some usecase thinking, at a higher development level.

There seem to be 3 different usecases for nextcloud installs:
1. personal nextcloud, only one user
2. team/company nextcloud. Users want to interact or should be able to.
3. cloud hosting for individuals. Users don't know each other and don't want to interact.

I feel like 3. is a rare case, and may even be a bad idea?!

@mburnicki I see why in your case users dont want other cloud users in their address book but all of your users can still find the other cloud users in the search bar or when sharing files, which may not be desirable either.

**Comment by skjnldsv** [comment]
Duplicate #243
