### ISSUE TITLE
Ambiguos checkbox in Addressbook settings

### ISSUE THREAD

**Issue by dcrobertson01** [nextcloud/contacts#2427]
If an address book is disabled, you get an unchecked checkbox labled 'Disabled'. This is contrary to the normal use of checkboxes. When an user looks at it, they see an item called Disabled and, as it is not checked, assume Disabled is not activated.

**Comment by kirmaha** [comment]
I had also issues to signal about that button.
 
 
1) "**Ambiguous label for the _Enabled_ button**"

**Actual behavior**
When an addressbook is « _Disabled_ », it is not shown on the user’s contact page. But it is still :
- synced with other devices through cardDAV
- shown to users you shared that addressbook with

**Expected behavior**
Regarding the effects of that button, its label should be changed from « _Enabled_ » to « _Shown_ » (or « _Displayed_ »).
 
 
2) "**Button not showing for shared addressbooks with _read-only_ permission**"

**Actual behavior**
As mentionned above, the « Enabled » button allows the user to hide contacts from an adressbook. Yet, that button is not shown for addressbooks shared by other users using _read-only_ permission (you can only delete those) : there is no way you can temporary hide contacts from shared addressbooks.

**Expected behavior**
Being able to hide addressbooks shared by other users (without deleting) the same way you do with your own addressbooks.
 
 
3) "**Button not working for shared addressbooks with _modify_ permission**"

**Describe the bug**
Impossible to uncheck « Enabled » box on an addressbook shared by another user, with _modify_ permission.

**Steps to reproduce the behavior:**

- Laura creates an addressbook.
- Laura shares that addressbook with Bob
- On Bob’s web interface, that addressbook appears with the « Enabled » box checked
- Bob clicks on that box to uncheck it, and receives an error message : « Toggling of address book was not successful »

*Expected behavior*
Having the possibility to hide addressbooks shared by other users (without deleting).
 
 
Thank you :-)
