### ISSUE TITLE
Contacts app is showing just a blank page

### ISSUE THREAD

**Issue by fenvarien** [nextcloud/contacts#2489]
### Describe the bug
If I try to use the contacts app the content doesn't show up. This happend after the update to version 4.0.5. The update seems to have failed and the version is still shown as 4.0.4.

**To Reproduce**
1. Update the app to the current version 4.0.5
Click on the contacts app.

**Expected behavior**
I expected to see my contacts and circles.
Version of the app should be 4.0.5

**Actual behavior**
I can only see a blank page.
The app version is still 4.0.4.

### Server configuration
**Operating system**: Ubuntu Server 20.04 LTS

**Web server:** Nginx

**Database:** PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg20.04+1) 

**PHP version: 8.0.12

**Nextcloud version: 22.2.0

**Contacts version: 4.04.->4.0.5

**Updated from an older Nextcloud or fresh install: updated

#### Browser log
Refused to execute script from 'https://cloud.rs-weil.de/apps/contacts/js/contacts-main.js?v=8e8d89fc-140' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by Emporea** [comment]
I have the same problem. 

Is this some sort of 4.0.4 joke?
Well done. :)

**Comment by ChristophWurst** [comment]
I'll have to have another look. I tested and it all worked here.

**Comment by ChristophWurst** [comment]
Please give https://github.com/nextcloud-releases/contacts/releases/tag/v4.0.6 a test

**Comment by ChristophWurst** [comment]
I know why 4.0.5 was a failure … I carefully built, tested and uploaded the artifact. But for the app store release I accidentally picked the source .tar.gz instead of my build … sorry for any trouble caused.

**Comment by Emporea** [comment]
Hey. Thank you for the quick fix!

4.0.6 works ! :)

**Comment by ChristophWurst** [comment]
Released :pray:.

**Comment by balajisivaraman** [comment]
@ChristophWurst, I just setup a brand new installation of Nextcloud on NixOS with Caddy as the web server. It worked like a charm. I then installed the Contacts app from the marketplace, and I can see that the version is 4.0.6. Unfortunately, I still see a blank page only.

This is the console error. I'm not sure if this is key: `The resource from “https://cloud.balajisivaraman.com/index.php/apps/dashboard/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).` I had originally set that header explicitly in my Caddyfile. But removing it doesn't help, since I believe it is being set by Nextcloud itself. (It also appears twice in my response. I'm not sure if it is related to https://github.com/nextcloud/server/issues/16476.)

![image](https://user-images.githubusercontent.com/1876249/140620443-6b8b20b7-5912-422e-974a-26565264d121.png)

Apologies for reusing this issue instead of creating a new one, since I thought it might be relevant. Please let me know if I need to create a new one with more details about my setup. Thanks in advance.
