### ISSUE TITLE
Allow encryption of contacts/parts of contacts via gpg/keybase or other

### ISSUE THREAD

**Issue by mannp** [nextcloud/contacts#274]
As the encryption module doesn't really add value according to most threads that I have read, perhaps allow users to encrypt all or part of a contacts details so confidential data is secured in case the nextcloud server is compromised.

The QNotes app does similar by allowing the importing of a keybase or gpg key and a button press allows encryption/decryption of that data.

Thanks for your consideration

**Comment by MariusBluem** [comment]
Backend -> discussion is already going on in server ;)

**Comment by 4jNsY6fCVqZv** [comment]
@MariusBluem I discovered this project at an open source conference. https://www.etesync.com/
Would Nextcloud integration be useful and conceivable to solve this issue?

**Comment by trymeouteh** [comment]
Please add the ability to have client side encryption with Nextcloud contacts. This will require Nextcloud making a Nextcloud contacts app for Android, iOS, Windows, Mac and Linux or having the Nextcloud clients add a contacts syncing integration into the app.

EteSync is the king of privacy and security for contacts since they have E2EE. I would like to see Nextcloud add this security and even allow the ability to edit the contacts in the browser using JavaScript to encrypt/decrypt the client side encryption.
