### ISSUE TITLE
REQ: list address books under "All contacts"

### ISSUE THREAD

**Issue by punkyard** [nextcloud/contacts#2870]
### Is your feature request related to a problem? Please describe.

In contacts
only "All contacts" and "Not grouped" are showed at the top of left menu

### Describe the solution you'd like

list of all the Address books listed under "all contacts"

### Additional context

give groups a different color - easily seen in the contact details

**Comment by jancborchardt** [comment]
Hi @punkyard – the list in the navigation is for user-defined groups (Family, Friends, etc whatever people choose). Address books are listed in "Settings" in the bottom left since most of the time people have only 1, and it’s fairly technical.

Groups in navigation | Contacts settings
-|-
![image](https://user-images.githubusercontent.com/925062/182350526-7d377bd0-df85-46e5-8185-28a45d01555f.png)|![image](https://user-images.githubusercontent.com/925062/182350488-44e82248-76d7-4dcb-a7cb-d7c15e4abdb6.png)
