### ISSUE TITLE
in-app search doesn't search in field "notes"

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/contacts#2925]
### Describe the bug

text from a contacts' "notes" field does not seem to get searched properly by the in-app search

### Steps to reproduce

1. create contact Diana and a few dummy contacts
2. create contact Jim, enter in notes "Diana's dad"
3. (close browser or restart computer or delete cookies or wait a day - not sure - if you just created the contacts it will probably work as expected, but when I use this with contacts from our address book it doesn't work as expected, see also additional info)
4. search for Diana

### Expected behavior

Diana and Jim should be shown in the list, because of the notes in Jim

### Actual behavior

only Diana is shown in the list

### Contact version

 4.2.0

### Operating system

?

### Additional info

* it works as expected in unified search (top right search symbol)
* it works as expected if you first look at Jim's contact details and then do the search (probably there is some kind of cache that gets filled while looking at the contact?)

(it's on managed hosting so I don't know php version etc but I can find out if it is really neccessary)

Nextcloud 23.0.8

**Comment by alexanderdd** [comment]
This is still a bug in NC 25.0.6 contacts 5.2.0

I think this used to work in the past, not sure until which version though...

IMO  it is pretty important to search all fields, not just the name... What do you think?

**Comment by aurisnoctis** [comment]
Can you still reproduce? Others had a similar problem and it seems gone for them: https://github.com/nextcloud/contacts/issues/922

Or could this be only seemingly so due to https://github.com/nextcloud/server/issues/24218? I came here because contacts weren't found with a search for some keyword that's in the "Notes" field. However, I started the search from "All contacts". That's the default name for an automatic group containing all my contacts and that name has a white space by default.

I can indeed reproduce the problem and it shows some strange behavior in the Contacts App of the web GUI:

* I have a certain keyword that's in the title of 1 contacts and in the "Notes" field of 2 other contacts.
* When I search for that keyword, only the one contact is found which has the search phrase in its title.
* When I then search for the **name** of another contact which has the keyword in the "Notes" but not in its name and click on it and then start a new search for the **keyword**, now 2 contacts are found: the one which has the keyword in the **name** and the one which has it in its "**Notes**" and on which I had clicked just before. But the third contact which has the keyword only in its "Notes" but which I **haven't clicked on just before is still not found**. Note that this is true no matter which contact was currently selected/active before doing the new search: the mentioned 2 contacts are found no matter whether the last click was on the contact with the keyword in the title or the keyword in the "Notes" - but the third is not found.
* Now, when I actively search for the name of the **third** contact (keyword only in "**Notes**" just as with the second contact) and once click on it, afterwards also that contact is found by search for the keyword, no matter which contact was clicked last. I just had to click on it once before a new search.
* When I reload the Nextcloud web interface, only the contact with the keyword in its "Name" is found when searching for the keyword. And the game as described above can be done again :arrow_right: **the search for fields other than "Name" seems to work only when the contacts have been in the cache of the browser before.**

**Comment by alexanderdd** [comment]
Yes, this problem still persists for me, NC 27.1.5, contacts 5.5.1

@ChristophWurst can you triage please?

**Comment by ChristophWurst** [comment]
what shall I do?

**Comment by alexanderdd** [comment]
@ChristophWurst This issue still has the label "Needs triage". I assumed that every new issue automatically gets this label, and someone from Nextcloud team needs to evaluate what to do with this issue (to develop, wontfix, ...), and adjust the labels...

Can you do that? Or did I misunderstand something?
