### ISSUE TITLE
Large contact photo preview

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#312]
**Users need an option to display large hi-res contact photo previews.**

There should be an option to display hi-res contact photo when a contact is open. It could appear in the top right-hand corner, and the header details contained to the left. The photo could come down further. We'll try and do a mock-up.

These days awareness of aesthetics, people with poor sight, and usability is heightened.

Mobile apps, and many web and desktop apps, understand that Users want beautiful apps, that make work/activities a pleasure.

Mobile apps on a tiny screen manage to display contact information with a nice large hi-res photo.

Yet, our webapp, even on a 24" screen fails to!

**Rationale**

Having the option of large contact photo is not just pretty - it's functional:

1)  increases usability - easy to figure who one is dealing with immediately
2)  better for those with poorer sight who can't make out pictorial details
3) seeing nice photos of people hugely encourages and improves workflow
4) Users are increasingly used to this on almost all their daily work and leisure apps on their phone and on the web (Skype, Telegram, Facebook, LinkedIN). 
Small pics make an app look and feel archaic and clunkly.

**Comment by skjnldsv** [comment]
But there is an high-res photo display!
![capture d ecran_2017-08-28_19-07-47](https://user-images.githubusercontent.com/14975046/29784420-3461cbaa-8c24-11e7-92ee-4e7deb3d91b2.png)

**Comment by olantrust** [comment]
Indeed, and that's great.

But not in the workflow of working with contacts.

Use any iPhone or Android or other modern contacts web app and large pics of contacts are displayed whilst working - meeting the rationale explained in the intro.

**Comment by skjnldsv** [comment]
Okay, I understand what you mean now.
Having it as a header?

I think this works great on mobile, but in desktop, not so much.
@irgendwie, @jancborchardt, @Henni what do you think?

**Comment by jancborchardt** [comment]
Yeah, the top left image is pretty big already, no?

**Comment by mburnicki** [comment]
Another point:

I know it's currently "trendy" to show contact photos in a circle shape, while formerly they were usually shown with a square shape. I'm maintaining a contacts list with more than 2700 entries, which has evolved over quite some years, and many of the entries are not persons with real faces, but organizations etc. where the contact photo is a square icon.

Now, if you look at the contacts list in Android then most of the icons are crippled since the display has changed to a circle shape, and the background is shown instead of the truncated parts of the image.

Until I've recently switched to nextcloud I've been using owncloud for quite some years, and even though their contacts app had a number of bugs, the contact photos were shown in a square shape, without being crippled.  I'd very much appreciate if there was at least a setting where you could select that the original square contact photos are shown in the contacts list.

I've not yet tried to look this up in the source code, but it shouldn't be too hard to call a function that resizes an image to square rather than round.

**Comment by juliushaertl** [comment]
@mburnicki Good point, although it will be somehow inconsistent to the avatars used anywhere else in Nextcloud, which are all round. An individual setting for UI variations is I guess nothing we want to have. Any comments, @nextcloud/designers ?

An easy workaround would be to use the new theming_customcss (https://apps.nextcloud.com/apps/theming_customcss) app with the following oneliner: 

`.contact__icon, .contactdetails__logo, .contactdetails__header avatar { border-radius: 0 !important; }`

**Comment by mburnicki** [comment]
@juliushaertl Thanks for the pointer, so I can at least try a local workaround to get it fixed for me.

**Comment by skjnldsv** [comment]
After thoughts, I'd rather focus on the workflow and I'm sure this is visually a great addition, but won't add much and rather clutter the ui a bit :)
Let's keep it simple ;)
