### ISSUE TITLE
Cannot save contact

### ISSUE THREAD

**Issue by EricDriussi** [nextcloud/contacts#3126]
### Describe the bug

Yet another issue of this kind (I've read pretty much all of them but can't pinpoint the culprit).

Basically, trying to create a new contact produces no error, but after a refresh the contact is gone.
It seems it never gets saved.

### Steps to reproduce

1. Try to create a contact
2. All is fine
3. Press F5
4. sad

### Expected behavior

I would expect the contact to get persisted.

### Actual behavior

Contact isn't there.

### Contact version

4.2.2

### Operating system

Linux 5.10.0-18-amd64 x86_64 (Debian Bullseye)

### PHP engine version

PHP 8.0

### Web server

Other

### Database

MySQL

### Additional info

I'm hosting the snap package (currently provides Nextcloud 24) on a VPS, behind a nginx reverse proxy.

I've read through all the similar issues I could find, so hopefully I'm not duplicating stuff.
Unfortunately in my particular case, there seems to be no significant error I can find.

The UI doesn't complain.
Checking the network tab in the dev tools reveals nothing (no 4** or 5** responses).
Neither the apache nor the nginx access or error logs seem to have anything strange.
mysql, php, and nextcloud logs are much the same.
Out of desperation, I've tried with different web browsers, clearing cache and cookies. Still nothing.

I can go for a huge log dump if that helps.
I just thought I'd wait to hear from you guys, see if there's any place in particular one might look into first.

Thanks in advance!!

**Comment by EricDriussi** [comment]
Oh forgot to mention, there are a bunch of TypeError in the browser console but I'm not sure they are particularly relevant.

```
TypeError: Cannot read properties of undefined (reading 'find')
    at contacts-main.js?v=450c21db:1:395077
    at Array.forEach (<anonymous>)
```

**Comment by Debianer** [comment]
I am having a similar issue. I am running the docker containers from here:

https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb/apache

Currently with 24.0.9, since I am pinning the Nextlcoud version in the YML. I would say this appeared after upgrading from 24.0.8 to 24.0.9. Calendar works fine.

For me, the ui complains. This is the error message:

"This contact is not yet synced. Edit it to save it to the server."

Also Sync fails. 

Here is some console output:

<html><body>
<span class="message-body-wrapper"><span class="tabpanel-summary-label headers-summary-label">Status</span><span class="tabpanel-summary-value status" data-code="400"><div class="requests-list-status-code status-code" data-status-code="400" data-code="400">400</div>Bad Request</span></span><span class="message-body-wrapper"><div class="headers-overview"><div class="summary"><div class="tabpanel-summary-container headers-summary"><span class="tabpanel-summary-label headers-summary-label">Version</span><span class="tabpanel-summary-value">HTTP/1.1</span></div><div class="tabpanel-summary-container headers-summary"><span class="tabpanel-summary-label headers-summary-label">Übertragen</span><span class="tabpanel-summary-value">816 B (262 B Größe)</span></div><div class="tabpanel-summary-container headers-summary"><span class="tabpanel-summary-label headers-summary-label">Referrer Policy</span><span class="tabpanel-summary-value">no-referrer-when-downgrade</span></div></div></div><ul class="accordion" tabindex="-1"><li id="responseHeaders" class="accordion-item accordion-open" aria-labelledby="responseHeaders-header"></li></ul></span><span class="message-body-wrapper"><div class="properties-view"><div class="tree-container">

  |  
-- | --
cache-control | no-store, no-cache, must-revalidate

</span>
</body>
</html>Status
400
Bad Request
VersionHTTP/1.1
Übertragen816 B (262 B Größe)
Referrer Policyno-referrer-when-downgrade

	
cache-control
	no-store, no-cache, must-revalidate
content-length
	262
content-security-policy
	default-src 'none';
content-type
	application/xml; charset=utf-8
date
	Thu, 23 Feb 2023 13:33:46 GMT
expires
	Thu, 19 Nov 1981 08:52:00 GMT
pragma
	no-cache
referrer-policy
	no-referrer-when-downgrade
strict-transport-security
	max-age=15768000
x-content-type-options
	nosniff
x-frame-options
	DENY
x-permitted-cross-domain-policies
	none
x-powered-by
	PHP/8.0.28
x-robots-tag
	none
x-xss-protection
	1; mode=block
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	de,en-US;q=0.7,en;q=0.3
Connection
	keep-alive
Content-Length
	258
Content-Type
	text/vcard; charset=utf-8
Cookie
	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; oc_sessionPassphrase=XXXXXXX
 nc_username=XXXXXXXXXXXXX
nc_session_id=7XXXXXXXXXcd37dfcd25d317f49f5
Depth
	0
DNT
	1
Host
	XXXXX
Origin
	https://XXXXXXX/
Referer
	https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-504278~contacts
requesttoken
	XXXXXXXXXXXXXXXXXXXXXXXXXXXX
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-origin
Sec-GPC
	1
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

    X-Requested-With
    	XMLHttpRequest

Uncaught (in promise) Error: 
    a dist.js:1
    i dist.js:1
    r dist.js:1
    i dist.js:1
    r dist.js:1
    i dist.js:1
    r dist.js:1
    onreadystatechange dist.js:1
    e dist.js:1
    e dist.js:1
    c dist.js:1

**Comment by Debianer** [comment]
Upgrading to Nextcloud 25 solved this issue for me.
