### ISSUE TITLE
prefer local users in mastodon avatar download

### ISSUE THREAD

**Issue by call-me-matt** [nextcloud/contacts#3210]
### Describe the bug

when downloading social avatars from mastodon, sometimes global users are found instead of the correct local one

### Steps to reproduce

1. Add `Greta@mastodon.social`
2. Click on `Get [avatar] from mastodon`
3. See it downloading the picture from `gretathunberg@mastodon.nu`

### Expected behavior

local users should be prioritized, searching on `mastodon.social` in this example

### Actual behavior

search prioritizes popular global accounts

### Contact version

5.0.3

**Comment by tcitworld** [comment]
A more exact fix would be to use Webfinger instead of the Mastodon API to make sure we have the right user (and bonus points for compatibility with other Fediverse software that don't implement the Mastodon API¹):

* ```
  GET https://server.tld/.well-known/webfinger?resource=acct:user@server.tld
  ```
* Find link with `rel=self` and `type=application/activity+json`, use the `href` value, then `GET` with `application/activity+json` `Accept` header
* Should give something like 
  ```
  GET https://server.tld/users/user
  ```
* Finally you just use the `icon`.`url` property.

¹ Even the Diaspora provider could be rewritten to something similar in the first part.

**Comment by call-me-matt** [comment]
good point to get the webfinger instead of searching! But then, one could also directly construct the userpage URI, right?
Search has the advantage of returning a JSON with the avatar directly. We had a html scraper here before switching to the API and I think its more robust to work with JSON.
