### ISSUE TITLE
Single column layout

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/contacts#3305]
### Is your feature request related to a problem? Please describe.

The current layout of Contacts looks misaligned and confusing, and fields jump around the screen on being added.

### Describe the solution you'd like

Single column layout, all the properties are arranged in one column, with another column for the `add new property` button in edit mode and contact quick actions and shared items in view mode.

![image](https://user-images.githubusercontent.com/52440189/231748464-39cc019e-a317-45e1-a271-65001583a94c.png)
![image](https://user-images.githubusercontent.com/52440189/231748352-ba00dde3-3987-416a-aab0-ae86f928b256.png)

Mobile:
![image](https://user-images.githubusercontent.com/52440189/231752991-84b7d2cf-6617-4d8a-88cf-9fb0b2911719.png)

- [x] Property type (`Home`, `Work`, etc) all have the same width
- [x] Input fields for each property all have the same width 
- [x] All input fields are left aligned
- [ ] Left align name and title + company (Alice Smith, Analyst at Incorporated GmbH) with the text in the left column (Phone, 1234123412, Address, etc)
- [x] Right align icon of each property (phone icon, email icon, etc) with type of property ("Home" in phone, "Home" in email, etc)
- [ ] Having one column only would leave a lot of whitespace on the right of the screen. Here, the "Add new property" button can go. This makes the position consistent no matter how many fields are added. 
- [ ] In view mode the quick actions and shared items could be shown on the right.
- [ ] In mobile view:
  - [ ] Property icon + label, and the meta data (`Home`, `Work`, etc. as well as `Postbox number`, `Street`, etc) is justified left 
  - [ ] Quick actions are shown at the top
  - [ ] Shared items are shown at the bottom 
  - [ ] "Add new property" button is also at the bottom as the last row.

cc @jancborchardt 

### Additional context

part of #1923

**Comment by ishaan730** [comment]
Hi @nimishavijay and @jancborchardt , I was impressed by your idea of using a single column layout for the contact page, as well as your updated design proposal. However, I've been doing some additional exploration on the same design pattern and have come up with some ideas to further improve the contact edit and view pages.

![Contact edit page](https://user-images.githubusercontent.com/49994669/232335544-25b35225-44a7-4bf1-bdc7-7e8f8cdbd106.jpg)

**To enhance the user experience of the page, I've implemented three changes:**

1. Added a sticky button at the bottom for easier navigation.
2. Grouped properties with clear labels and separators for better organization.
3. Added outer borders around icon buttons to make them more noticeable.

_And here’s reason why we should consider these changes_ 

**1. Sticky button at the bottom**
Easy access: By placing the buttons at the bottom of the page and making them sticky, users can easily access them no matter how far down they scroll on the page. This eliminates the need to scroll back up to the top of the page to perform an action, saving time and effort.

Visual cues: Sticky buttons can serve as a visual cue that the user has reached the end of the page and can take action. This can be especially helpful on longer pages that require a lot of scrolling, as it can prevent users from getting lost or disoriented.

Consistency: Placing the buttons in a consistent location (at the bottom of the page) can also help with learnability and memorability. Once users have interacted with the buttons a few times, they will know where to find them in the future, reducing cognitive load and making the experience more intuitive.

**2. Grouped properties with clear labels and separators**
Organization: Grouping similar properties together with proper labels and separators can make the contact details page more organized and easier to navigate. Users can quickly locate the section they need and edit the relevant information without having to scroll through a long list of fields.

Clarity: Providing labels for each group of properties can help users understand what type of information they are editing. For example, grouping email addresses together and labeling them as such makes it clear to users that they are editing email addresses and not phone numbers.

Efficiency: By grouping related properties together, users can edit multiple fields at once without having to jump around the page. For example, if a user needs to update several email addresses, they can easily do so in one section rather than having to navigate to different parts of the page.

Scalability: As more properties are added to the page, grouping them with proper labels and separators makes it easier to maintain a clean and organized layout. This ensures that the user interface remains usable and efficient even as the amount of information grows.

**3. Outer borders around icon buttons**
Clear Visual Cues: Adding an outer border around an icon provides a clear visual cue to users that the icon is clickable and serves as a button. This can help to prevent confusion and ensure that users can easily identify interactive elements.

Consistency: By using consistent visual design elements across your user interface, you can create a more cohesive and intuitive experience for users. Using an outer border around icons on buttons helps to maintain this consistency and reinforce the idea that these elements are interactive.

Better Accessibility: For users with certain visual impairments, such as color blindness, an outer border can provide additional contrast and help to distinguish the icon from its background. This can improve accessibility and ensure that all users are able to interact with your interface effectively.

Improved Touch Target: On touch screens, icons can be small and difficult to tap accurately. By adding an outer border, you increase the touch target area, making it easier for users to interact with the button on mobile/tablet devices.

![Contact View page](https://user-images.githubusercontent.com/49994669/232336073-cf2a834e-eb70-44f1-97c6-a233e3e027da.jpg)

**Comment by jancborchardt** [comment]
@ishaan730 hi there, thanks for the detailed explanations and mockups! Here’s my design review and feedback:
- The title of "Create contact" and "Contact details" are not necessary – the name of the contact are the most important thing on this page :)
- The layout between editing and viewing changes a bit much. It is intentionally kept similar in Nimisha’s design so it’s easy to find one’s way around
- We intentionally do not separate between "First name" and "Last name" since some languages do not conform to that. They might just have one name, or put last name before first name, etc. So it is just a flexible input field, with an optional more detailed name input.
- The button wording "Save" and "Cancel" is very generic – it could be improved to "Save contact" and "Reset changes"
- In "View" mode, the "Close" button is not really necessary? What would happen when you press it – I assume the right view would just get empty? Doesn’t seem needed.
- The button placement on the bottom boxes the layout in a lot for just 2 buttons. It would be better if we use the placement of "Edit" on the top right, and simply make it sticky. This is also for example similar placement to the top right actions in Talk and Forms.
- The labels for "Home"/"Work", street, city etc are right-aligned to make it easier readable together with which property they belong to. See also [macOS Contacts](https://support.apple.com/en-sg/guide/contacts/welcome/mac)
- The moving of "Mail", "Call", "Message", "Share" quick actions to the left column seems good as it’s more present! :)
- Horizontal lines as separators is someting we do not really use, unless it is for really separate sections (like in settings). We would simply use vertical whitespace in this case.
- Similarly for the icon buttons, our [tertiary button](https://nextcloud-vue-components.netlify.app/#/Components/NcButton) is text/icon only. If we want a button style with a border around, we should introduce it in the components to make it consistent.

Let me know what you think! :) @nimishavijay anything else?

**Comment by jancborchardt** [comment]
And @ishaan730 if you want to contribute more, it would be best to look at issues which don’t have mockups yet. :) Since there are not so many designers in open source there are limited resources, and having 2 mockups for the same thing can create confusion – it’s better to spread it out evenly, do you know what I mean? :)

**Comment by jancborchardt** [comment]
@ishaan730 if you send me your email address (you can find my contact info on my website :) I can give you a proper guest account on our Nextcloud instance too. Then you can be logged in to the Design channel more permanently and also use it on mobile, if you like. :)

**Comment by jancborchardt** [comment]
@nimishavijay can you create a new issue with the mockup with the quick actions, shared items, and "Events with you" so that is preserved? :)
