### ISSUE TITLE
Unstructured address shows all value at "Post office box"

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3404]
### Describe the bug

System address book contacts have no structured address. Yet the value is wrongly shown as one in read-only mode.

### Steps to reproduce

1. Add an address to your Nextcloud profile and set the scope to local
2. Open your own system address book card

### Expected behavior

The address shows unstructured

### Actual behavior

The address shows structured and my location shows in the "Post office box" row

![image](https://github.com/nextcloud/contacts/assets/1374172/61535a98-3a1c-4cf9-8b15-a796f7957bb8)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
I think we just show the value in the first structured input. *Other* is the ADR property type.

Cloning the contact into a writeable address book allows me to see the same contact in edit mode:

![image](https://github.com/nextcloud/contacts/assets/1374172/8c51da5b-fd09-4862-8990-87ae4f8f94ab)

**Comment by JohannesGGE** [comment]
I think it is also confusing that there is a Location and a Address prop. In the profile settings, we say Location but we actually mean Address?

**Comment by JohannesGGE** [comment]
@ChristophWurst I checked the card and the address seems to be saved structured.
`ADR;TYPE=HOME:ADRESSE;;;;;;`
So this is more a SAB issue, isn't it? Should be saved `ADR;TYPE=HOME:;ADRESSE;;;;;`

**Comment by ChristophWurst** [comment]
If that's the issue then yes. We write the ADR at https://github.com/nextcloud/server/blob/0ad56e5752eb8386252ea76d583d009b6d4456bf/apps/dav/lib/CardDAV/Converter.php#L94-L96. 

>       Experience with vCard 3 has shown that the first two components
>       (post office box and extended address) are plagued with many
>       interoperability issues.  To ensure maximal interoperability,
>       their values SHOULD be empty.

From https://www.rfc-editor.org/rfc/rfc6350.html#section-6.3.1

Maybe we should fill *locality*.

**Comment by ChristophWurst** [comment]
Tricky and risky but what we *could* do it allow people to enter the location in a format we can interpret. Some help text can explain the format. E.g. *Berlin* for city=Berlin and *Berlin, Germany* for city=Berlin;country=Germany. Like split at every "," and depending on number of parts we assume different semantics of the parts.

@jancborchardt @nimishavijay what do you designers think?

**Comment by ChristophWurst** [comment]
There is no unstructured address in cards AFAIK

**Comment by jancborchardt** [comment]
One part of why we call it "Location" in the profile is because it's for your Profile, and Social. So it would be that people put in (as Christoph said) either city or Country (most likely) as on Twitter and Mastodon for example.

It would be a bit strange to call the field in Profile "Address", as it sounds like you are supposed to put in a proper address.

Likewise, it would be off to call the field in the Contact "Location".

I'd also say that maybe just putting a placeholder example in the location field like "City" and simply mapping it to city then would be an easy quick win?


@ChristophWurst additionally, cause you mentioned "Company" and "Organization" – these we should just standardize though. "Company" and "Job title" sort of seems the standard (comparing to Apple and Google), so we should use those terms in both Contacts and Profile.
