### ISSUE TITLE
Sort order of the contact groups

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#344]
Currently there seems to be no specific sort order of the contact groups in the navigation:
![screenshot from 2017-09-21 00-58-05](https://user-images.githubusercontent.com/925062/30671621-3508dfd4-9e68-11e7-89e4-91d226671b38.png)
It’s neither alphabetically nor by amount of people in it.

Ideal would be to sort the groups by number of people in it, biggest groups on top.

**Comment by xraMsamohT** [comment]
> Ideal would be to sort the groups by number of people in it, biggest groups on top.

I prefer an alphabetical sort order, so it would be nice to be able to choose both, alphabetically or by number of contacts.

**Comment by alexboorman** [comment]
If you want a fast workaround for this _(that does not allow you to punch **All Contacts** to the top of the list due to the compiled controller for nextcloud, would need to add a subfunction for ordering to adjust a specific id)_ you can add this line to `templates/groupList.html` for the ng-repeat statement 
```javascript
ng-repeat="group in ctrl.groups | fieldFilter: ctrl.group | orderBy: name"
```
