### ISSUE TITLE
remove a group from a contact

### ISSUE THREAD

**Issue by pc-erwin** [nextcloud/contacts#3516]
### Describe the bug

It is not posible to remove a group from a contact. If more than one group in the contact,

### Steps to reproduce

1. Go to any 'contact'
2. Click on 'edit'
3. Click on 'groups'
3. Scroll down to the group you want to remove
4. Nothing happend

### Expected behavior

The Group will remove from the contact.

### Actual behavior

The Group still in the contact.

### Contact version

5.3.2

### Operating system

Ubuntu 22.04

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by brievenbusalex** [comment]
I have the same issue, also using contact app v5.2.3 on NC 27.0.1.

Somehow if you edit a contact and try to delete a contact group, the select button on the group for deleting it is not visible:

![image](https://github.com/nextcloud/contacts/assets/10253686/21054754-960f-480c-b555-ff66ece22d5b)

Then I made a work-around with custom css-code to overrule the original css-code to make the select button visible:

Original code:

`[data-v-7f976c8b] .vs__deselect {
    display: none;
}`

Custom code:

`section.contact-details .vs__deselect {
    display: block !important;
}`

![image](https://github.com/nextcloud/contacts/assets/10253686/bc8cddb4-87c3-47c6-bc9d-a41ab62d2058)

Then the select button to delete the group is visible and it is possible to delete the group for this contact.

Hopefully this helps tracking the problem.

**Comment by AbeilleVerte** [comment]
Hello, I have the same problem  , when I click on the contact group when editing, it does not delete the contact  from the group anymore.

Thanks for the help

**Comment by alexanderdd** [comment]
Editing of contact groups is still broken (NC 26.0.5  Contacts 5.3.2 Firefox 117 and also Chromium 116.0.5845.96). 

This issue is labelled "to triage" - who can triage it?

@ChristophWurst you labelled this issue "needs info" - what info do you need?

@hamza221: 
* in your screencast it it visible that the "x" icon to delete a group is not there anymore, and that the checkmark for activated groups in the dropdown is not there anymore - this already makes this section unusable
* you are able to add/ a group by clicking it in the dropdown, which I am not. I am using a shared address book, maybe that's a reason? Or what other info do you need?

@brievenbusalex  Thanks for the workaround, now we can at least delete groups via the "x". Scrolling through the groups is only possible with shift+Mousewheel though, the horizontal scrollbar is not visible in Firefox (Chromium shows a much wider scrollbar).

IMO the field to show groups is too small, it should be big enough to see all groups, or at least up to 10, with vertical scrolling, not horizontal scrolling, should I open a new issue about this or can it stay here?

**Comment by hamza221** [comment]
probably cause by https://github.com/nextcloud/contacts/pull/3452

**Comment by hamza221** [comment]
@alexanderdd  
> IMO the field to show groups is too small, it should be big enough to see all groups, or at least up to 10, with vertical scrolling, not horizontal scrolling, should I open a new issue about this or can it stay here?
Please create a separate issue
