### ISSUE TITLE
Selection dialogue for address book import always jumps to "Contacts"

### ISSUE THREAD

**Issue by PaulchenPlump** [nextcloud/contacts#3611]
### Describe the bug

I have more than one address book and would like to import a larger number of contacts from a file. Unfortunately, the selection dialogue always jumps to "Contacts" (and then imports them there) and does not let me select another address book.

### Steps to reproduce

1. Go to the contacts settings
2. Click on import button
3. Try to change the address book -> only "Contacts" is selected

### Expected behavior

Another address book should be selectable.

### Actual behavior

Multiple address books are displayed, but regardless of what is selected, it always changes to "Contacts".

### Contact version

at least 5.3.2 and 5.4 affected 

### Operating system

Installed on Archlinux, tested with Firefox on Linux and Android as well as Edge on Windows

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

**Comment by fuse314** [comment]
I have the same issue.
The problem lies in vue-select, trying to convert the whole `contact` object to a JSON string:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'e'
    |     property 'publicCalendarHome' -> object with constructor 'w'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at vue-select.js:1:16138
    at Array.filter (<anonymous>)
    at o.findOptionFromReducedValue (vue-select.js:1:16076)
    at o.setInternalValueFromOptions (vue-select.js:1:13845)
    at o.handler (vue-select.js:1:13404)
    at qe (vue.runtime.esm.js:1863:26)
    at vn.run (vue.runtime.esm.js:4584:9)
    at An (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
We @ vue.runtime.esm.js:1897
Ve @ vue.runtime.esm.js:1888
He @ vue.runtime.esm.js:1848
qe @ vue.runtime.esm.js:1871
vn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
```

The select should probably just return the contact object's "id" property instead of the object itself.

The contact import functionality is not working for me right now.

**Comment by fuse314** [comment]
After a bit of debugging, I found the probable cause:
[SettingsImportContacts.vue L41](https://github.com/nextcloud/contacts/blob/a6c0a1fa4a91668cebc94dd3ce09add1a10931e0/src/components/AppNavigation/Settings/SettingsImportContacts.vue#L41)
the `model` of NcSelect is bound to the `selectedAddressbook` computed property. When the getter is invoked, it returns the actual addressbook object instead of the mapped `options` object (only containing ìd` and `displayName`).

It should be bound to the `importDestination` data property.

➡️ can anyone from the Nextcloud Contacts Team verify and fix this? Thank you.
