### ISSUE TITLE
newly created contacts disappear after leaving contacts

### ISSUE THREAD

**Issue by thorsten-schwartz** [nextcloud/contacts#3718]
### Describe the bug

After starting contacts in Nextcloud for the first time, there is initially no address book, not even the system contacts.
After creating an address book (e.g. Test) and creating a contact (e.g. Max Test) in this address book, everything initially works as expected.
If you now switch back to Nextcloud, e.g. to Files and then back to Contacts, all contacts and the address book itself are deleted again. The GUI of Contacts is as it was originally without any data.
The behavior is identical for all users.

I have already deleted contacts (also from the webspace itself) and reinstalled them.
php occ dav:sync-system-addressbook was also unsuccessful.

![1](https://github.com/nextcloud/contacts/assets/54764492/31f005c8-079b-4a4a-b3af-03009204ff3c)
![2](https://github.com/nextcloud/contacts/assets/54764492/9a8d0cd2-27a5-4a6e-a7ef-465bf09390dd)
![3](https://github.com/nextcloud/contacts/assets/54764492/2bef8777-81a8-4c0d-92fa-3df0b337fb3e)
![4](https://github.com/nextcloud/contacts/assets/54764492/aaa8d12b-15a0-431f-b637-d2300640d6cd)
![5](https://github.com/nextcloud/contacts/assets/54764492/e7ba4056-3e2e-4646-b5ff-8034205c73bf)
![6](https://github.com/nextcloud/contacts/assets/54764492/7fb58145-7a33-4435-a963-bb6daa2d4815)
![9](https://github.com/nextcloud/contacts/assets/54764492/075de26b-a354-44a1-901c-057bdcf7bc72)

### Steps to reproduce

1. switch to contacts
2. create an address book (system address book is missing!)
3. create a contact
4. leaving contacts
5. switch to contacts
6. contacts and address book have disappeared

### Expected behavior

contacts and address books should stay
system address book should be available

### Actual behavior

contacts and address book have disappeared

### Contact version

contacts: 5.4.2

### Operating system

Linux Ubuntu 22.04 Server

### PHP engine version

Other

### Web server

Nginx

### Database

MariaDB

### Additional info

PHP 8.2
Nextcloud 27.1.4

**Comment by hamza221** [comment]
Hello can you please share relevant log messages and/or network requests

**Comment by meeque** [comment]
Have you found a solution for this problem @thorsten-schwartz?  Or at least identified the root cause?

I've run into the same problem last week. I'm a Nextcloud newbie, so my install is pretty fresh. Seems to work fine otherwise. Here are some specs:

```
OS:                  Ubuntu 22.04.3 (Linux 6.2.0-1018-aws x86_64)
Docker Engine:       24.0.5
Docker Image:        nextcloud:apache
  +- image digest:   sha256:0d231d59967d997141be8016c41df5e05f03137abbf741a8f0be2c0a8af80cf6
  +- Apache httpd:   2.4.5
  +- PHP:            8.2.15
  +- Nextcloud:      28.0.2.5
  \- Contacts App:   5.5.1
MySQL:               8.3.0
nginx reverse proxy: 1.25.3
```

I've checked the logs in the Nextcloud web  UI (under Administration/Logging) and the Apache request and error logs, but could not find anything suspicious. What should I be looking for @hamza221?

Does anyone know where the Contacts app would normally store its data? DB or FS? Which tables or dirs?

**Comment by meeque** [comment]
Ok, I figured it out. In my case, this problem has been caused by a **reverse-proxy misconfiguration**. I had only allow-listed certain HTTP methods: The common ones, plus the ones from **WebDAV** ([RFC 2518](https://datatracker.ietf.org/doc/html/rfc2518)). However, the Nextcloud Contacts app (and Calendar app) relies on some methods from the **WebDAV Versioning Extensions** ([RFC 3253](https://datatracker.ietf.org/doc/html/rfc3253)).

For now, I've reconfigured my nginx reverse proxy to allow all HTTP methods. Contacts now work like a charm. Even the address books and contacts that I had created before fixing this were there. Apparently the problem only prevented read access, not write access.

@thorsten-schwartz, could your problems be caused by something similar? Maybe check for 4xx responses in the browser dev tools. In my case, I noticed several requests with the **`REPORT`** method, when navigating to the Contacts app. My reverse proxy was blocking them with a 403 status response:

![Nextcloud-Contacts-Blocked-WebDAV-Methods](https://github.com/nextcloud/contacts/assets/901490/4d918ac3-5daf-4ae6-b9e0-45bab36fd4ad)

These requests could also be seen in the logs of my reverse proxy. But not in the logs of the Apache httpd that runs Nextcloud itself. They never got that far.

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
