### ISSUE TITLE
Number of Contacts shows just 999+ instead of real number

### ISSUE THREAD

**Issue by MarkusH1975** [nextcloud/contacts#445]
### Steps to reproduce
1. add more the 999 contacts, e.g. 1255

### Expected behaviour
Should show e.g. 1255 instead of 999+

### Actual behaviour
Shows 999+

**Nextcloud version:** (see Nextcloud admin page)
V12.0.3
**Contacts version:** (see Nextcloud apps page)
V2.0.1

![contacts](https://user-images.githubusercontent.com/30717540/33207094-aa844f74-d10c-11e7-8541-152d105d0742.png)

**Comment by irgendwie** [comment]
This was/is a design choice - do you have a need for the exact number of contacts?

**Comment by mburnicki** [comment]
If the real number of contacts is shown anyway, why not show it? This would really help verifying that everything works as expected.

The current situation with PIM apps is generally pretty unsatisfying, IMO. I've got a huge number (~3000) of contacts in different address books that evolved over several years. Originally this was hosted with owncloud, and you could at least edit all properties with the contacts app. 

Some time ago I migrated to nextcloud, using several different clients, each of which has some limitations:

- This contacts app (v2.0.1) is unable sort the contacts list reliably. I'd prefer sorting contacts from all addressbooks by "last name, first name", but even if I select sorting by last name I can't see that this is done correctly. Also, some contacts that are known to be available in the database are not shown at all. Don't know why, and didn't have time to try to find out, yet. Anyway, if you don't see a properly sorted list it's hard to find out. If the true number of contacts was shown I could at least find out if all contacts have been loaded, or some are missing. Loading the contacts from nextcloud is *very* slow. 

- The cardbook addon for Thunderbird has made some good progress in the recent past. It loads the contacts much faster, but also some contacts are missing in the displayed list. Interestingly, the contacts missing here are different ones than in the contact app.

Eventually there are some entries in the nextcloud DB that have invalid characters or something due to bugs in earlier versions of some client or owncloud server version, but with a huge number of contacts it's hard to find out which ones are missing, and why, and fix it.

- The KDE PIM software shows all contacts, even those that are skipped by nextcloud/contact and cardbook. So you can at least verify that a specific contact is in the cloud DB. However, doing changes in this software removes some information when the contact is saved back in the DB.

- Android contacts editor seems to load all contacts, too, and it basically seems to have the least number of bugs. It has at least a statistics menu wherecan quickly check how many contacts are in each address book.

I don't want to start ranting here, but just make clear why I found it important to see some information if it's available anyway.

**Comment by jsavalle** [comment]
+1 for real number or at least for some doc on what should I tweek to get the real number of contact.

**Comment by dhowe** [comment]
+1 for real number option

**Comment by skjnldsv** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Yes, let's show the full number here.

(The 999+ was taken over from the News app for unread items where exactness is not that important.)

**Comment by skjnldsv** [comment]
@jancborchardt actually it's coming from the design guidelines (not written from me)

**Comment by jancborchardt** [comment]
Yeah, that part was written based on what we learnt from the News app. :) That app is what we developed the whole #app-navigation structure from, back in the day. ;)

However, stuff changes or is different across apps – here for Contacts we should show the exact number. :)

**Comment by suntala** [comment]
Could I please be assigned this ticket?

**Comment by skjnldsv** [comment]
@suntala please do! :)

**Comment by suntala** [comment]
pr: #509 (worked as Team Popcorn for RGSoC 2018 with @sleepypioneer)

**Comment by sleepypioneer** [comment]
pr: #540 (worked as Team Popcorn for RGSoC 2018 with @suntala)
