### ISSUE TITLE
First Name and Last Name do not get populated when only a Formatted Name is entered

### ISSUE THREAD

**Issue by blind-coder** [nextcloud/contacts#458]
### Steps to reproduce
1. Create new contact with only a Formatted Name

### Expected behaviour
First Name and Last Name should be populated by splitting the Formatted Name

### Actual behaviour
First Name and Last Name are not populated.

### Server configuration

**Operating system**: Debian Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )

**Nextcloud version:** 12.0.4

**Contacts version:** 2.0.1

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:** No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "<some id>",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.example.com"
        ],
        "datadirectory": "\/home\/www\/example.com\/nc\/htdocs\/data",
        "overwrite.cli.url": "https:\/\/nc.example.com",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud_production",
        "dbhost": "mysql.example.com",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** https

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FireFox ESR

**Operating system:** Debian GNU/Linux Unstable

**CardDAV-clients:** Contacts App, DMFS.org CardDAV Sync, RCMCardDAV

### Logs

Not Applicable

Mentioning https://github.com/blind-coder/rcmcarddav/issues/213 for reference.

**Comment by skjnldsv** [comment]
We can't predict how this will happen. What if the name is Dr XXX xxx ? Will this be split on the first space? 
You need to populate it manually with the detailed name form :)

**Comment by blind-coder** [comment]
While this may not violate specs, it is literally the opposite of what every other addressbook frontend, from ownCloud to Android and iOs, does. As a side note, while `N` does not NEED to be populated in a vcard, it `SHOULD` be. I wonder how many other clients this will break.

**Comment by skjnldsv** [comment]
@blind-coder We're just following the rfc requirements here. FN is mandatory, N is not! :)
I, from my side, have no use of the N field, most of my contacts (maybe all) are only populated with the FN field. My android is pretty fine with it :)

I need to take a look at how android auto split it! It might be interesting

**Comment by mburnicki** [comment]
Of course, if you have only a couple of contags with names like "Mom", "Dad", "Peter" it makes no big difference.

However, if you have a large number of contacts or even address books then it's most welcome if you can sort and display the entries by "last name, first name" so it's really helpful if the details are populated, too, and IMO it's good practice if the frontend software makes this as easy as possible.

Maybe try the cardbook addon for Thunderbird, which tries to separate the components automatically when imported from an email address, and even provides a way to swap last name / first name easily, if required.

Also keep in mind that you may have the address of a restaurant or hotel in your address book, where it doesn't make much sense to distinguish between first name and last name, and a good solution is to have the full name and last name set to the same string. This can be done manually, but at least this doesn't mess up a displayed contact list that is sorted by "last name, first name".

**Comment by skjnldsv** [comment]
> Also keep in mind that you may have the address of a restaurant or hotel in your address book, where it doesn't make much sense to distinguish between first name and last name, and a good solution is to have the full name and last name set to the same string. This can be done manually, but at least this doesn't mess up a displayed contact list that is sorted by "last name, first name".

This is why the FN field exists. Why would we break things by wrongly assign first and last name with same data?
We should not create our own rules here. The rfc rules are here for a reason! :)

**Comment by mburnicki** [comment]
I think you misunderstood. I said that there are **special cases** like hotel names where it makes sense to set the "last name" field to the same as the "full name" in order to get a properly sorted list when the list is sorted by "last name, first name". Since these are special cases, I wouldn't expect from an app to be able to detect and handle this automatically.

However, if a contact editor app helps filling up the vcard fields in a way that is correct in usual cases then this just makes life easier for the folks who work with that app, even if sometimes (e.g. in case of a hotel name) manual interaction is required.

Is the RFC saying that you must not set the detailed name fields, or does it specify that this has to be done manually?

BTW, I just tried with the contacts editor of my Android phone. If I create a new contact and just enter the full name "Hello world" then "Hello" is also copied into the first name, and "World" into the last name, so in my contact list (which is sorted by "last name, first name" the new contact is immediately listed as "World, Hello". If I synchronize the new contact via NC to my Cardbook addon in Thunderbird then this als looks correctly, as expected. 

So how does this break any rule if an apptries to make users' life as easy as possible?

**Comment by skjnldsv** [comment]
> So how does this break any rule if an apptries to make users' life as easy as possible?

I completely agree with you :)
I'm not saying this should not be done, but that right now we are providing it manually.

> BTW, I just tried with the contacts editor of my Android phone. If I create a new contact and just enter the full name "Hello world" then "Hello" is also copied into the first name, and "World" into the last name

That's why I said :)
> I need to take a look at how android auto split it! It might be interesting
 
The rfc rules are saying that FN is required and used by default to be read as the "displayed name".
While the N field is only there to detail the correct name (like firs, last, surname, prefix, title...) That's why I said that using it to enter an hotel name twice with first and last name is not the proper way to do it. You can, but I will definitely not agree with that ;)

**Comment by blind-coder** [comment]
The RFC states that `FN` MUST be present, while `N` SHOULD be present if the vcard follows X.520
FN: https://tools.ietf.org/html/rfc6350#section-6.2.1
N: https://tools.ietf.org/html/rfc6350#section-6.2.2

Insofar I agree with @skjnldsv that the behaviour is not wrong. Unexpected maybe, but not wrong.
I only noticed because in RCMCardDAV we use the absence of an N tag to infer `X-ABShowAs` behaviour (see: https://www.w3.org/2002/12/cal/vcard-notes.html). Sometimes, Company entries lack the `X-ABShowAs` key, lack the `N` key but have an `FN` and `ORG` key (https://tools.ietf.org/html/rfc6350#section-6.6.4). In that case, we show the vcard as a company entry, setting the user-visible value of `FN` to that of `ORG`.
From the PR I got on that, that behaviour is in line with Apple`s addressbook software. I have no access to that for testing, though.

**Comment by skjnldsv** [comment]
From android source code:
 ```
* A dedicated editor for structured name.  When the user collapses/expands
 * the structured name, it will reparse or recompose the name, but only
 * if the user has made changes.  This distinction will be particularly
 * obvious if the name has a non-standard structure. Consider this structure:
 * first name="John Doe", family name="".  As long as the user does not change
 * the full name, expand and collapse will preserve this.  However, if the user
 * changes "John Doe" to "Jane Doe" and then expands the view, we will reparse
 * and show first name="Jane", family name="Doe".
```

Basically it's automatically splitting with `String[] strings = phoneticName.split(" ", 3)` 
https://android.googlesource.com/platform/packages/apps/ContactsCommon/+/5ade0bb/src/com/android/contacts/common/util/NameConverter.java#188

**Comment by Henni** [comment]
This feature has been on my mind since the initial release of the app.
The main issue why this was postponed multiple times, is that it is difficult to define the "usual case".
There are titles, multiple surnames, compound surnames... This combined with multiple languages is just awful to support. There are libraries like https://github.com/joshfraser/JavaScript-Name-Parser, but most of the libraries don't support multiple languages and are always just heuristical approaches.

We wanted to get the foundations right, before creating new issues by adding heuristics to this app.
And as long as we are still fighting with other issues, I doubt this is a feature we'll find time to implement. (Just my two cents on this. Contributions are always welcome :wink:)

**Comment by mburnicki** [comment]
@skjnldsv You wrote:
> While the N field is only there to detail the correct name (like firs, last, surname, prefix, title...) That's why I said that using it to enter an hotel name twice with first and last name is not the proper way to do it. You can, but I will definitely not agree with that ;)

Which fields would you use instead?
Have you ever tried this?

What would you expect to see for a hotel contact if your contact list is sorted by "lastname, firstname" but you have only entered the full name but the first name and last name fields are just empty? You'd see an empty entry (or just a comma ',' if the app developer doesn't check if fields are empty or not) at the beginning or end of the list instead of the hotel name inserted at the expected position.

And please, don't just look how **this+* app behaves, but also what happens if I use this app to add the contact to the NC data base, and some other app to show the contacts provided by the NC data base. ;-)

**Comment by skjnldsv** [comment]
I use the FN field. Rarely the N :)
It's a really good question for the hotel. ORG should be defined as the hotel organisation name, but the FN should be used to defined which details the vcard belongs to. Like

> FN:Luxury V's hotel reception
> ORG:Luxury V

**Comment by mburnicki** [comment]
@skjnldsv Agreed. ;-)
However, this doesn't fix the problem when different fields are displayed due to a different sort order. ;-)

**Comment by skjnldsv** [comment]
Indeed! :p
