### ISSUE TITLE
Create a group from the group/left pane

### ISSUE THREAD

**Issue by GLLM** [nextcloud/contacts#563]
Hi all !

Would it be possible to let us create new group directly from the group / left pane ?
At the moment, one must create it from within a contact (maybe becaus eyou cannot have empty groups) ?

A way to do this would be to add a drop down arrow next to the "+ New Contact" to select a "+ New group"

![image](https://user-images.githubusercontent.com/3989573/40770887-35d99b36-64bc-11e8-82a6-4d43e947c3df.png)

Thanks

**Comment by jancborchardt** [comment]
Yes, this is a good point. Currently it’s only possible by adding a group to a contact, which is a bit confusing if you don’t know it.

It should be an entry on the bottom of the group list called: `+ New group` (looking like a group entry, but half-opacity)

cc @suntala @sleepypioneer maybe something for you? :)

**Comment by skjnldsv** [comment]
We can't do that unless we use the vcard-groups fonction of the frc vcard.
Currently a group is stored inside each contacts, so empty groups cannot exists :)

**Comment by jancborchardt** [comment]
@skjnldsv the way the technology works and the way we present it to people are 2 different things. ;)

We could do a number of things, for example having that group in a database, or local storage, etc etc – until a user is added to it.

**Comment by skjnldsv** [comment]
@jancborchardt actually I wanted to implement a dual support of this on the new contacts app.
Have the default groups stored on individual vcards and sync them to the proper contacts vcard as well. Like so we'll improve our compatiibility with ios and android and various vcard managers ;)

> the way the technology works and the way we present it to people are 2 different things. ;)

Unfortunately that's correct when you don't have big rfc compliances like we have on the contacts. We can't really do whatever we want on this or it doesn't make sense for the user. If we implement custom made solutions, we will set us aside from the others contacts manager. We can't add every feature we want because we're tight with the vcard format :(

**Comment by GLLM** [comment]
Mmmhhhh .... I see what you both mean... not sure if this Feature Request will remain opened for long.

**Comment by skjnldsv** [comment]
@GLLM We'll see, but I really want to add such feature :)
It's just a bit tricky ;)

**Comment by skjnldsv** [comment]
Related #213
