### ISSUE TITLE
'Contact disappeared in server' on server when parsing error

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#762]
We should make sure to fix the contact or at least have a proper error stating this contact have an issue.

**Comment by franck-eyraud** [comment]
Hello,

I have this issue for some contacts of my address book (25 out of 1000) that have a bad format. I can see them when downloading the full address book, but don't see them in the Contacts App. I identified the error in the vCard thanks to the console (`EMAIL;TYPE=INTERNET\\:user@domain.tld`, the two backlsashes should not be there), but I'm wondering what is the way to fix them ? 

Since contacts are not listed, no way to edit them. Is there a way to upload directly the correct vCard ? But then, how to delete the bad one ?

Thank you
