### ISSUE TITLE
Displayed name field not automatically populated since vue.js

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#821]
## Expected behavior
If you create a new contact and choose the "Detailed Name" property, the entered data should automatically populate the Displayed Name field as in previous versions.

## Current behavior
If you create a new contact and choose the "Detailed Name" property, the entered data is not used to populate the Displayed Name field anymore as in previous versions. The Displayed Name field stays empty and need to be manually entered too.

![20190105_nc_contacts_detailed_name_not_populating_displayed_name](https://user-images.githubusercontent.com/2572764/50722941-09351e80-10d7-11e9-81b9-9100ed80d11e.png)

### Steps to reproduce
1. Open the Contacts app
2. Choose **New contact**
3. Choose **Add new property** and select **Detailed name**
4. Enter data into the **Detailed name** fields **Prefix**, **First name** and **Last name**
5. Check out the **Displaye name** field at the top of the record
-> The field is not automatically populated

#### Server Configuration
OS: Linux 3.16.50
Web server: Apache2 2.4.37
Database: MariaDB 10.2.19
PHP version: 7.2.13
Nextcloud version: 15.0.0
Contacts app version: 3.0.1

#### Client Configuration
Browser: Mozilla Firefox 64.0
Operating system: Windows 10

**Comment by skjnldsv** [comment]
Aaah, I can't find the other issue. Someone asked about this not long ago.
Basically we removed the feature because people wanted to keep track of this.
https://github.com/nextcloud/contacts/issues/671

Though we could make sure that:
1. we auto-populate the displayname field IF it still says 'New Contact'
2. populate the detailed name fields if
  1. displayname is not 'New Contact'
  2. detailed name fields are empty

**Comment by j-ed** [comment]
I think, as long as no-one has entered any data into the display name field it should automatically be populated. It looks like your examples are covering all use cases.

**Comment by skjnldsv** [comment]
Glad you like it then :)
