### ISSUE TITLE
Support multiple type declaration

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#942]
Looking at the rfc: https://tools.ietf.org/html/rfc6350#section-6.4.1

>      The default type is "voice".  These type parameter values can be
>      specified as a parameter list (e.g., TYPE=text;TYPE=voice) or as a
>      value list (e.g., TYPE="text,voice").  The default can be
>      overridden to another set of values by specifying one or more
>      alternate values.  For example, the default TYPE of "voice" can be
>      reset to a VOICE and FAX telephone number by the value list
>      TYPE="voice,fax".

- [ ] Workaround to migrate the parameter list to a value list
- [x] Waitning for https://github.com/mozilla-comm/ical.js/issues/343 https://github.com/mozilla-comm/ical.js/pull/388

**Comment by jellium** [comment]
Hello, I understand this issue is related to the way iOS handles types set as a value list (e.g. doesn't handle the syntax like `TYPE="VOICE,CELL"` as defined by the standard but accepts `TYPE=VOICE,CELL` instead). However, is there any quick fixe for Nextcloud × iOS users who would accept to have the Nextcloud vcf file not formatted properly (i.e. with types as a value list but without quotes)? I tried to manually import, remove quotes and export but this doesn't work.
Thanks a lot.

**Comment by Nemental** [comment]
Something new in here?

**Comment by skjnldsv** [comment]
@Nemental still waiting for https://github.com/mozilla-comm/ical.js/issues/343

**Comment by skjnldsv** [comment]
FIX HAVE BEEN MERGED :tada:

**Comment by skjnldsv** [comment]
Waiting for new ical.js release now

**Comment by skjnldsv** [comment]
Next contacts release will fix this :D

**Comment by skjnldsv** [comment]
Please help test the new release (link in first post): https://github.com/nextcloud/contacts/pull/1579

**Comment by apastuszak** [comment]
I don't think this is fixed.  I'm running Contacts 3.3.0 on Nextcloud 18.0.4 and this is what I see with my Nextcloud contacts:

![icloud_contact](https://user-images.githubusercontent.com/3401054/82172690-e5701400-9898-11ea-906d-5887784d4fb4.PNG)

Note how the home number still shows **"HOME** instead of **home**.

**Comment by veritas06** [comment]
I'm in the same boat as apastuszak. Tried editing an existing contact & even creating a new one, but still seeing the same issue. I can run through & document all the steps again, but still has not been working for me.

Nextcloud 18.0.3
Contacts 3.3.0

**Comment by apastuszak** [comment]
Here is what I am seeing.  If I create a new contact in Nextcloud and then iOS syncs it, and I export it as vcf, I see this line:

```TEL;TYPE="HOME,VOICE":(xxx) xxx-xxxx```

And the iPhone displays **"HOME**

If I then edit the contact and change the phone type to home, the vcf export from Nextcloud shows this:

```TEL;type=HOME;type=VOICE;type=pref:(xxx) xxx-xxxx```

**Comment by skjnldsv** [comment]
Yep, the issue is the quote now.
Multiple types are different.

Also, this is not released as far as I recall

**Comment by nsrafk** [comment]
How is this progressing? I really cant migrate away from iCloud contacts until this works :-)

Good job everybody - sadly i can’t contribute with :[

**Comment by F3ELING1337** [comment]
Yes I would also like to know how the status of this is? Currently on NC 20.0.2 and iOS 14.2:
Contacts on iOS synced with NC still show things like "CELL or "HOME instead of 'valid' values.
Thanks for all your help to the developers!

**Comment by veritas06** [comment]
Any update on this? I see the issue is closed but it's still not resolved.

**Comment by veritas06** [comment]
Can we get this re-opened since the issue is not resolved?

**Comment by tamburra** [comment]
This has been an issue for a long time and still is with all current releases as of Feb 5, 2021. Would love for this to get reopened and possibly resolved.
